Repository open-learning-exchange/planet, pull requests merged in 2018-07, with the labels that each got.

#1464 [#1456] Throw error when login is not sucessful (fixes #1456)
  src/app/login/login-form.component.ts
Labels: in progress

#1478 [#1469] Increase couchdb http request size (connects #1469)
  couchdb-setup.sh
Labels: in progress

#1457 [#1439] Add margin to mat-raised-buttons (fixes #1439)
  src/app/configuration/configuration.component.ts
Labels: in progress

#1517 [#1513] Feedback resource link (connects #1513)
  src/app/feedback/feedback-view.component.html
Labels: in progress

#1516 [#1507] exam-form debug off (connects #1507)
  src/app/exams/exams-add.component.html
Labels: in progress

#1505 [#1504] login language orientation (connects #1504)
  src/app/login/login-form.component.html
  src/app/login/login.component.html
Labels: in progress

#1518 [#1511] manager sync refresh button (connects #1511)
  src/app/manager-dashboard/manager-sync.component.html
Labels: in progress

#1525 [#1508] non-mandatory drop down issue in Resource add / update form (connects #1508)
  src/app/resources/resources-add.component.html
Labels: in progress

#1501 [#1455] Load the same page on changing Language (fixes #1455)
  src/app/shared/planet-language.component.html
  src/app/shared/planet-language.component.ts
Labels: in progress

#1327 [#1290] Dialog List when there is no record shows **Deselect all** (connects #1290)
  src/app/shared/dialogs/dialogs-list.component.html
  src/app/shared/dialogs/dialogs-list.component.ts
Labels: in progress

#1493 1470 meetup datetime (connects #1470)
  src/app/meetups/add-meetups/meetups-add.component.html
  src/app/meetups/add-meetups/meetups-add.component.ts
  src/app/validators/custom-validators.ts
Labels: in progress

#1489 [#1419] Error for invalid date (connects#1419)
  src/app/shared/form-error-messages.component.ts
  src/app/users/users-update/users-update.component.ts
  src/app/validators/custom-validators.ts
Labels: in progress

#1530 Update version
  package.json
Labels: in progress

#1447 [#1303] community-notification (connects #1303)
  src/app/community/community.component.ts
  src/app/configuration/configuration.component.ts
  src/app/home/home.component.html
  src/app/notifications/notifications.component.ts
Labels: in progress

#1335 [#1332] Drop Down List on Profile Option (connects #1332)
  src/app/home/home.component.html
  src/app/shared/dialogs/change-password.directive.ts
  src/app/shared/dialogs/planet-dialogs.module.ts
  src/app/users/users-profile/users-profile.component.html
  src/app/users/users-profile/users-profile.component.ts
  src/app/users/users.module.ts
  tslint.json
Labels: in progress

#1506 Try to fix the ng e2e test #1436
  .travis.yml
  .travis/travis_utils.sh
  Vagrantfile
  angular.json
  e2e/login.e2e-spec.ts
  package.json
Labels: in progress, reviewed

#1553 [#1546 remove request] (connects #1546)
  src/app/courses/courses.component.html
Labels: in progress

#1554 [#1551] hover on submission row list (connects #1551)
  src/app/submissions/submissions.component.ts
Labels: in progress

#1555 [#1544] course feedback (connects #1544)
  src/app/courses/courses.component.html
  src/app/feedback/feedback-view.component.html
Labels: in progress

#1558 [#1547] Resubmit rating does not update other details (connects #1547)
  src/app/resources/rating-resources/resources-rating.component.ts
Labels: in progress

#1559 [#1537] hide satellite user (connects #1537)
  src/app/meetups/view-meetups/meetups-view.component.ts
Labels: in progress

#1538 [#1523] Wrap username and add toltip (fixes? #1523)
  src/app/courses/progress-courses/courses-progress-leader.component.html
  src/app/courses/progress-courses/courses-progress-leader.scss
Labels: in progress

#1521 Learner progress view
  src/app/courses/courses-router.module.ts
  src/app/courses/courses.module.ts
  src/app/courses/courses.service.ts
  src/app/courses/progress-courses/courses-progress-chart.component.html
  src/app/courses/progress-courses/courses-progress-chart.component.ts
  src/app/courses/progress-courses/courses-progress-chart.scss
  src/app/courses/progress-courses/courses-progress-leader.component.html
  src/app/courses/progress-courses/courses-progress-leader.component.ts
  src/app/courses/progress-courses/courses-progress-learner.component.ts
  src/app/courses/progress-courses/courses-progress.component.html
  src/app/courses/progress-courses/courses-progress.scss
  src/app/dashboard/dashboard-tile.component.html
  src/app/submissions/submissions.service.ts
Labels: in progress

#1531 Update vagrant to expose port for docker
  Vagrantfile
Labels: in progress

#1568 Update version
  package.json
Labels: in progress

#1569 1535 feedback search filter (connects #1535)
  src/app/feedback/feedback.component.html
  src/app/feedback/feedback.component.ts
Labels: in progress

#1571 [#1566] add exam validation message (connects #1566)
  src/app/exams/exams-add.component.html
  src/app/exams/exams-add.component.ts
Labels: in progress

#1556 [#1549] Icon for gender on profile (connects #1549)
  src/app/users/users-update/users-update.component.html
  src/styles.scss
Labels: in progress

#1573 #1552 members hover (connects #1552)
  src/app/home/home.component.html
Labels: in progress

#1572 [#1548] update config back button (connects #1548)
  src/app/configuration/configuration-router.module.ts
  src/app/configuration/configuration.module.ts
  src/app/login/login-router.module.ts
  src/app/manager-dashboard/manager-dashboard-configuration.component.ts
  src/app/manager-dashboard/manager-dashboard.module.ts
  src/app/manager-dashboard/manger-dashboard-router.module.ts
Labels: in progress

#1592 [#1576] community notification filter (connects #1576)
  src/app/community/community.component.html
  src/app/community/community.component.ts
Labels: in progress

#1593 [#1578] exam question validator (connects #1578)
  src/app/exams/exams-add.component.ts
Labels: in progress

#1594 [#1586] login reroute (connects #1586)
  src/app/login/login-form.component.ts
Labels: in progress

#1010 [#997] Show parent version on manager dashboard (connects #997)
  couchdb-setup.sh
  src/app/configuration/configuration-guard.service.ts
  src/app/manager-dashboard/manager-dashboard.component.html
  src/app/manager-dashboard/manager-dashboard.component.ts
  src/app/shared/user.service.ts
Labels: in progress

#1557 [#1539] course view layout issue (connects #1539)
  src/app/courses/view-courses/courses-view.scss
Labels: in progress, in review

#1574 [#1502] Reset satellite pin (#1502)
  src/app/configuration/configuration.component.ts
  src/app/manager-dashboard/manager-dashboard.component.html
  src/app/manager-dashboard/manager-dashboard.component.ts
  src/app/shared/user.service.ts
Labels: in progress

#1481 [#1472] Invalid password warning on replicator (connects #1472)
  src/app/manager-dashboard/manager-sync.component.ts
  src/app/shared/sync.service.ts
Labels: in progress, in review

#1442 [#1363] Show exam of different step when no submissions are present (fixes #1363)
  src/app/courses/progress-courses/courses-progress-leader.component.ts
Labels: in progress

#1598 Update version
  package.json
Labels: in progress

#1613 [#1375] Resources Mock Data: Publisher to publisher (connects #1375)
  design/resources/resources-mockup.json
Labels: in progress

#1589 [#1577] Exam title prefill (connects #1577)
  src/app/exams/exams-add.component.ts
Labels: in progress

#1611 [#1608] not to invite enrolled members (connects #1608)
  src/app/meetups/view-meetups/meetups-view.component.ts
Labels: in progress

#1612 [#1580] Feedback whole row clickable (connects #1580)
  src/app/feedback/feedback.component.html
Labels: in progress

#1610 [#1607] remove header from user table (connects #1607)
  src/app/users/users.component.html
Labels: in progress

#1561 [#1550] Removing meetup from dashboard (connects #1550)
  src/app/dashboard/dashboard.component.ts
Labels: in progress, in review

#1615 Add script to convert js to json for design docs (fixes #79)
  couchdb-setup.sh
  design/create-design-docs.js
Labels: in progress

#1614 Add parentProtocol environment variable
  src/app/configuration/configuration.component.ts
  src/app/shared/couchdb.service.ts
  src/app/shared/sync.service.ts
  src/environments/environment.prod.ts
  src/environments/environment.test.ts
  src/environments/environment.ts
Labels: in progress

#1601 [#1543] Give the join/leave button more 'presence' (fixes #1543)
  src/app/meetups/view-meetups/meetups-view.component.html
Labels: in progress

#1618 [#1606] add course simultaneously (connects #1606)
  src/app/courses/courses.component.html
  src/app/courses/courses.component.ts
  src/app/resources/resources.component.ts
  src/app/shared/utils.ts
  src/app/users/users.component.ts
Labels: in progress

#1458 [#1451] Set max-width of img to 100px (fixes #1451)
  src/app/users/users.component.ts
Labels: in progress

#1624 Fix upgrade script
  docker/planet/Dockerfile
Labels: in progress

#1625 Upgrade version
  package.json
Labels: in progress

#1651 [#1636] search bar of team (connects #1636)
  src/app/teams/teams.component.ts
Labels: in progress

#1631 [#1630] Team Database (connects #1630)
  .travis.yml
  couchdb-setup.sh
Labels: in progress

#1627 [#1621] swap team and meetups (connects #1621)
  src/app/dashboard/dashboard.component.html
Labels: in progress

#1648 [#1641] snackbar message in library (connects #1641)
  src/app/shared/planet-message.service.ts
Labels: in progress

#1650 [#1635] remove addteam from user
  src/app/users/users.component.html
  src/app/users/users.component.ts
Labels: in progress

#1656 Add teams to route with background (fixes #1637)
  src/app/home/home.component.ts
Labels: in progress

#1655 Narrower left section of dashboard
  src/app/dashboard/dashboard.scss
Labels: in progress

#1658 Add members to teams (fixes #1629)
  src/app/meetups/view-meetups/meetups-view.component.ts
  src/app/shared/dialogs/dialogs-list.service.ts
  src/app/teams/teams-view.component.html
  src/app/teams/teams-view.component.ts
Labels: in progress

#1660 Update version
  package.json
Labels: in progress

#1666 [#1643] show version on http://server/version (fixes #1643)
  docker/planet/Dockerfile
  docker/planet/default.conf
  docker/planet/rpi-Dockerfile
Labels: in progress

#1662 [#1644] Improve success message on upgrade (fixes #1644)
  src/app/upgrade/upgrade.component.html
Labels: in progress

#1667 Add script to generate yml file based on current commit, version, and…
  .gitignore
  docker/generate_yml.sh
  package.json
Labels: in progress

#1661 [#1642] Remove usage of bash in upgrade script (fixes #1642)
  docker/planet/Dockerfile
  docker/planet/upgrade.sh
Labels: in progress

#1673 [#1634] team member limit (connects #1634)
  src/app/teams/teams-view.component.html
  src/app/teams/teams-view.component.ts
  src/app/teams/teams.service.ts
Labels: in progress

#1657 [#1646] Enable submit on empty list (connects #1646)
  src/app/manager-dashboard/manager-dashboard.component.ts
  src/app/shared/dialogs/dialogs-list.component.html
  src/app/shared/dialogs/dialogs-list.component.ts
Labels: in progress

#1675 Update version
  package.json
Labels: in progress

#1357 [#1356] Course rating (connects #1356)
  src/app/app.module.ts
  src/app/configuration/configuration.module.ts
  src/app/courses/courses.component.html
  src/app/courses/courses.component.ts
  src/app/courses/courses.module.ts
  src/app/courses/courses.service.ts
  src/app/courses/progress-courses/courses-progress-learner.component.ts
  src/app/courses/view-courses/courses-view.component.html
  src/app/courses/view-courses/courses-view.component.ts
  src/app/exams/exams.module.ts
  src/app/home/home.module.ts
  src/app/login/login.module.ts
  src/app/manager-dashboard/manager-dashboard.module.ts
  src/app/meetups/meetups.module.ts
  src/app/resources/resources.component.html
  src/app/resources/resources.module.ts
  src/app/resources/resources.service.ts
  src/app/resources/view-resources/resources-view.component.html
  src/app/resources/view-resources/resources-view.component.ts
  src/app/shared/dialogs/dialogs-form.component.html
  src/app/shared/dialogs/planet-dialogs.module.ts
  src/app/shared/forms/form-error-messages.component.spec.ts
  src/app/shared/forms/form-error-messages.component.ts
  src/app/shared/forms/planet-forms.module.ts
  src/app/shared/forms/planet-rating-stars.component.html
  src/app/shared/forms/planet-rating-stars.component.ts
  src/app/shared/forms/planet-rating.component.html
  src/app/shared/forms/planet-rating.component.ts
  src/app/shared/forms/planet-stacked-bar.component.ts
  src/app/shared/forms/rating.service.ts
  src/app/shared/mangoQueries.ts
  src/app/shared/planet-forms.module.ts
  src/app/submissions/submissions.module.ts
  src/app/users/users.module.ts
Labels: in progress

#1664 [#1647] Added retry option when the docker timeouts (fixes #1647)
  src/app/upgrade/upgrade.component.ts
  src/app/upgrade/upgrade.scss
Labels: in progress

#1565 [#1342] Add il8n section to style guide (fixes #1342)
  Style-Guide.md
Labels: in progress

#1693 [#1679] Update current user_id when getListAndColumns is called (fixes #1679)
  src/app/shared/dialogs/dialogs-list.service.ts
Labels: in progress

#1699 [#1692] add resource and exam icon (connects #1692)
  src/app/courses/add-courses/courses-step.component.html
Labels: in progress

#1698 [#1691] logout position (connects #1691)
  src/app/home/home.component.html
Labels: in progress

#1697 [#1677] invite member filter (connects #1677)
  src/app/teams/teams-view.component.ts
Labels: in progress

#1701 [#1695] Add feedback to meetup (connects #1695)
  src/app/feedback/feedback-view.component.html
  src/app/meetups/meetups.component.html
Labels: in progress

#1696 [#1680] switch meetups and teams (connects #1680)
  src/app/home/home.component.html
Labels: in progress

#1702 [#1683] meetup view cleanup (connects #1683)
  src/app/meetups/meetups.component.html
  src/app/meetups/view-meetups/meetups-view.component.html
Labels: in progress

#1676 Show version of parent & planet (connects #1671)
  couchdb-setup.sh
  src/app/configuration/configuration-guard.service.ts
  src/app/manager-dashboard/manager-dashboard.component.ts
  src/app/shared/couchdb.service.ts
  src/app/shared/user.service.ts
Labels: in progress

#1719 [#1710] findAll for notifications (connects #1710)
  src/app/notifications/notifications.component.ts
Labels: in progress

#1721 [#1714] hide rating for parent (connects #17147)
  src/app/courses/view-courses/courses-view.component.html
  src/app/resources/view-resources/resources-view.component.html
Labels: in progress

#1706 [#1632] teamlist button response (connects #1632)
  src/app/teams/teams.component.ts
Labels: in progress

#1722 fixes feedback form focus
  src/app/shared/dialogs/dialogs-form.service.ts
Labels: in progress

#1449 [#1448] Clean configuration replicator add replicator on admin login (connects #1448)
  src/app/community/community.component.ts
  src/app/configuration/configuration.component.ts
  src/app/login/login-form.component.ts
  src/app/manager-dashboard/manager-dashboard.component.html
  src/app/manager-dashboard/manager-dashboard.component.ts
  src/app/shared/sync.service.ts
Labels: in progress, in review

#1717 couchdb 2.1.2
  Vagrantfile
  docker/generate_yml.sh
  docker/planet.yml
Labels: in progress

#1496 [#1494] Send item to parent (connects #1494)
  src/app/courses/courses.component.html
  src/app/courses/courses.component.ts
  src/app/resources/resources.component.html
  src/app/resources/resources.component.ts
Labels: in progress

#1723 Update version
  package.json
Labels: in progress

#1619 [#1604] multiple meetup join (connects #1604)
  src/app/meetups/meetups.component.html
  src/app/meetups/meetups.component.ts
  src/app/meetups/meetups.service.ts
Labels: in progress

#1628 [#1623] archive team (connects #1623)
  src/app/teams/teams-view.component.html
  src/app/teams/teams-view.component.ts
  src/app/teams/teams.component.html
  src/app/teams/teams.component.ts
  src/app/teams/teams.service.ts
Labels: in progress

#1735 [#1730] Ignore planet yml file (connects #1730)
  .gitignore
Labels: in progress

#1720 Resource tags
  couchdb-setup.sh
  design/courses/course-validators.js
  design/courses/course-validators.json
  design/create-design-docs.js
  design/nations/nation-validators.js
  design/nations/nation-validators.json
  design/resources/resources-design.js
  design/resources/resources-design.json
  src/app/app.module.ts
  src/app/resources/resources-add.component.html
  src/app/resources/resources-add.component.ts
  src/app/resources/resources.component.html
  src/app/resources/resources.component.ts
  src/app/shared/couchdb.service.ts
  src/app/shared/forms/planet-forms.module.ts
  src/app/shared/forms/planet-tag-input.component.html
  src/app/shared/forms/planet-tag-input.component.ts
  src/app/shared/forms/tags.service.ts
  src/app/shared/material.module.ts
  src/app/shared/table-helpers.ts
Labels: in progress

#1590 [#1587] Update config admin on admin profile update (connects #1587)
  src/app/shared/user.service.ts
  src/app/users/users-update/users-update.component.ts
Labels: in progress

#1707 [#1622] send notification to all team (connects #1622)
  src/app/teams/teams-view.component.ts
  src/app/teams/teams.component.ts
  src/app/teams/teams.service.ts
Labels: in progress

#1733 [#1726] configuration creating new doc (connects #1726)
  src/app/configuration/configuration.component.ts
Labels: in progress, in review

#1718 [#1711] team view request pending highlight (connects #1711)
  src/app/teams/teams-view.component.html
Labels: in progress

#1620 [#1560] Received course indicator (connects #1560)
  src/app/courses/courses.component.html
  src/app/courses/courses.component.ts
  src/app/courses/courses.module.ts
  src/app/resources/resources.component.html
  src/app/resources/resources.component.ts
  src/app/resources/resources.module.ts
  src/app/shared/couchdb.service.ts
  src/app/shared/planet-local-status.component.ts
  src/app/shared/shared-components.module.ts
  src/styles.scss
Labels: in progress, in review

#1529 [#1200] Add loading spinner after submission (fixes #1200)
  src/app/resources/resources-add.component.html
  src/app/resources/resources-add.component.ts
  src/app/resources/resources.module.ts
  src/app/shared/dialogs/dialogs-loading.component.html
  src/app/shared/dialogs/dialogs-loading.component.ts
  src/app/shared/dialogs/planet-dialogs.module.ts
  src/app/shared/material.module.ts
  src/app/shared/planet-language.module.ts
  src/app/shared/submit.directive.ts
Labels: in progress

#1740 Update version
  package.json
Labels: in progress

#1752 New Crowdin translations
  src/i18n/messages.som.xlf
Labels: in progress

#1750 Switch from tags to labels in app
  src/app/resources/resources-add.component.html
  src/app/resources/resources.component.html
Labels: in progress

#1756 New Crowdin translations
  src/i18n/messages.ara.xlf
  src/i18n/messages.som.xlf
  src/i18n/messages.spa.xlf
Labels: in progress

#1757 [#1703] Add more timeouts messages (fixes #1703)
  src/app/upgrade/upgrade.component.ts
Labels: in progress

#1741 [#1638] team view layout (connects #1638)
  src/app/teams/teams-view.component.html
Labels: in progress

#1759 [#1688] notification styling (connects #1688)
  src/app/home/home.component.html
  src/app/home/home.scss
Labels: in progress

#1763 Update package.json
  package.json
Labels: in progress

#1764 fix somali
  src/i18n/messages.som.xlf
Labels: in progress

#1767 Update package.json
  package.json
Labels: in progress
