Repository open-learning-exchange/planet, pull requests merged in 2018-04, with the labels that each got.

#552 Add arrow_back icon in communities list (fixes #551)
  src/app/community/community.component.html
  src/app/home/home.component.ts
Labels: in progress

#550 544 advance search course (connect #544)
  src/app/courses/courses.component.html
  src/app/courses/courses.component.ts
  src/app/shared/table-helpers.ts
Labels: in progress

#565 Update version
  package.json
Labels: in progress

#440 [#433] connects nation community (connects #433)
  couchdb-setup.sh
  design/community/community-mockup.json
  design/nations/nations-mockup.json
  design/security-update/security-update.json
  src/app/community/community.component.html
  src/app/community/community.component.ts
  src/app/configuration/configuration.component.html
  src/app/configuration/configuration.component.ts
  src/app/courses/courses-router.module.ts
  src/app/courses/courses.component.html
  src/app/courses/courses.component.ts
  src/app/home/home-router.module.ts
  src/app/home/home.component.ts
  src/app/login/login-form.component.ts
  src/app/manager-dashboard/manager-dashboard.component.ts
  src/app/meetups/meetups-router.module.ts
  src/app/meetups/meetups.component.html
  src/app/meetups/meetups.component.ts
  src/app/nation/nation.component.html
  src/app/nation/nation.component.ts
  src/app/resources/rating-resources/resources-rating.component.html
  src/app/resources/rating-resources/resources-rating.component.ts
  src/app/resources/resources-router.module.ts
  src/app/resources/resources.component.html
  src/app/resources/resources.component.ts
  src/app/resources/resources.service.ts
  src/app/resources/view-resources/resources-view.component.html
  src/app/resources/view-resources/resources-view.component.ts
  src/app/shared/auth-guard.service.ts
  src/app/shared/couchdb.service.ts
  src/app/shared/user.service.ts
  src/environments/environment.prod.ts
  src/environments/environment.test.ts
  src/environments/environment.ts
Labels: in progress

#567 [#560] Create user shelf while creating user (connects #560)
  src/app/configuration/configuration.component.ts
  src/app/login/login-form.component.ts
Labels: in progress

#568 [#505] add allDocs method on couchService (connects #505)
  src/app/community/community.component.html
  src/app/community/community.component.ts
  src/app/configuration/configuration.component.ts
  src/app/courses/courses.component.ts
  src/app/feedback/feedback.component.ts
  src/app/meetups/meetups.component.ts
  src/app/nation/nation.component.ts
  src/app/shared/couchdb.service.ts
Labels: in progress

#597 Fix admin undefined
  src/app/configuration/configuration.component.ts
Labels: in progress

#545 [#486] Meetup (connects #486)
  src/app/dashboard/dashboard.component.ts
  src/app/meetups/add-meetups/meetups-add.component.html
  src/app/meetups/add-meetups/meetups-add.component.spec.ts
  src/app/meetups/add-meetups/meetups-add.component.ts
  src/app/meetups/constants.ts
  src/app/meetups/meetups-add.component.html
  src/app/meetups/meetups-add.component.ts
  src/app/meetups/meetups-router.module.ts
  src/app/meetups/meetups.component.html
  src/app/meetups/meetups.component.ts
  src/app/meetups/meetups.module.ts
  src/app/meetups/meetups.service.ts
  src/app/meetups/view-meetups/meetups-view.component.html
  src/app/meetups/view-meetups/meetups-view.component.spec.ts
  src/app/meetups/view-meetups/meetups-view.component.ts
Labels: in progress

#548 [#537] Resign and admission added(connects #537)
  src/app/courses/courses.component.html
  src/app/courses/courses.component.ts
  src/app/dashboard/dashboard.component.ts
Labels: in progress

#578 [#572] Only admin log into parent planet (connects #572)
  src/app/home/home.component.ts
  src/app/login/login-form.component.ts
Labels: in progress

#605 Update version
  package.json
Labels: in progress

#610 remove docker/planet-dev
  docker/README.md
  docker/planet-dev/Dockerfile
  docker/planet-dev/rpi-Dockerfile
Labels: in progress

#611 Fix Travis docker login prompt
  .travis/travis_utils.sh
Labels: in progress

#618 [#617] remove mesage variable and model object (connect #617)
  src/app/login/login-form.component.ts
Labels: in progress

#599 Adjust the layout of nation component (fixes 559)
  src/app/home/home.component.ts
  src/app/nation/nation.component.html
Labels: in progress

#623 Add navbar shadow
  src/app/_variables.scss
  src/app/home/home.component.html
  src/app/home/home.scss
Labels: in progress

#569 [#561] user profile reworked (connects #561)
  src/app/users/users-profile/users-profile.component.html
  src/app/users/users-profile/users-profile.component.ts
  src/styles.scss
Labels: in progress

#608 [#596] Password change sync with parent user (connects #596)
  src/app/users/users-profile/users-profile.component.ts
Labels: WIP, in progress

#641 Update version
  package.json
Labels: in progress

#642 Start course revision
  src/app/courses/add-courses/courses-add.component.html
  src/app/courses/add-courses/courses-add.component.ts
  src/app/courses/add-courses/courses-add.scss
  src/app/courses/add-courses/courses-step.component.html
  src/app/courses/add-courses/courses-step.component.ts
  src/app/courses/constants.ts
  src/app/courses/courses.module.ts
  src/app/shared/material.module.ts
Labels: in progress

#655 Delete planet dev ymls
  docker/planet-dev.yml
  docker/rpi-planet-dev.yml
Labels: in progress

#582 [#574] manager dashboard route fix (connects #574)
  src/app/courses/courses-router.module.ts
  src/app/courses/courses.component.html
  src/app/courses/courses.component.ts
  src/app/courses/view-courses/courses-view.component.html
  src/app/courses/view-courses/courses-view.component.ts
  src/app/home/home-router.module.ts
  src/app/home/home.module.ts
  src/app/manager-dashboard/manager-dashboard.component.ts
  src/app/manager-dashboard/manager-dashboard.module.ts
  src/app/manager-dashboard/manger-dashboard-router.module.ts
  src/app/meetups/meetups-router.module.ts
  src/app/meetups/meetups.component.html
  src/app/meetups/meetups.component.ts
  src/app/meetups/view-meetups/meetups-view.component.html
  src/app/meetups/view-meetups/meetups-view.component.ts
  src/app/resources/resources-router.module.ts
  src/app/resources/resources.component.html
  src/app/resources/resources.component.ts
  src/app/resources/view-resources/resources-view.component.html
  src/app/resources/view-resources/resources-view.component.ts
Labels: in progress

#612 [#603] remove object and array mixed
  src/app/home/home.component.ts
Labels: in progress

#659 Update version
  package.json
Labels: in progress

#663 no notification icon change
  src/app/home/home.component.html
Labels: in progress

#664 [#626] Resources advance search (connects #626)
  src/app/resources/resources.component.html
  src/app/resources/resources.component.ts
  src/app/shared/table-helpers.ts
Labels: in progress

#660 [#628] aaded home svg image
  src/app/app.component.ts
  src/app/home/home.component.html
  src/assets/icons/home.svg
Labels: in progress

#644 [#625] resource article date shortend (connects #625)
  src/app/resources/resources-add.component.html
  src/app/resources/resources-add.component.ts
Labels: in progress

#670 [#669] course manage update step
  src/app/courses/add-courses/courses-add.component.ts
Labels: in progress

#570 [#566] Add user to shelf (connects #566)
  src/app/dashboard/dashboard.component.ts
  src/app/users/users.component.html
  src/app/users/users.component.ts
Labels: in progress

#662 Update database field name to keep consistent camelcase
  couchdb-setup.sh
  src/app/community/community.component.html
  src/app/community/community.component.ts
  src/app/configuration/configuration.component.html
  src/app/configuration/configuration.component.ts
  src/app/courses/courses.component.ts
  src/app/courses/view-courses/courses-view.component.ts
  src/app/home/home.component.html
  src/app/home/home.component.ts
  src/app/login/login-form.component.ts
  src/app/manager-dashboard/manager-dashboard.component.ts
  src/app/meetups/meetups.component.ts
  src/app/meetups/view-meetups/meetups-view.component.ts
  src/app/nation/nation.component.html
  src/app/nation/nation.component.ts
  src/app/resources/resources.component.ts
  src/app/resources/view-resources/resources-view.component.ts
  src/app/shared/languages.ts
  src/app/shared/user.service.ts
  src/app/users/users-profile/users-profile.component.ts
Labels: in progress

#676 [#674] Remove unused import Location
  src/app/users/users-update/users-update.component.spec.ts
Labels: in progress

#673 [#667] delete step from course
  src/app/courses/add-courses/courses-add.component.html
  src/app/courses/add-courses/courses-add.component.ts
  src/app/courses/add-courses/courses-step.component.html
  src/app/courses/add-courses/courses-step.component.ts
Labels: in progress

#684 [#680] Odd time closing of mat expansion pannel fixed (connects #680)
  src/app/courses/add-courses/courses-step.component.html
Labels: in progress

#688 [#666] Move Up Down of step
  src/app/courses/add-courses/courses-add.component.html
  src/app/courses/add-courses/courses-add.component.ts
  src/app/courses/add-courses/courses-step.component.html
  src/app/courses/add-courses/courses-step.component.ts
Labels: in progress

#689 Update version
  package.json
Labels: in progress

#650 Remove overwriting styles for .view-container (fixes #562)
  src/app/resources/view-resources/resources-view.scss
  src/app/users/users-profile/users-profile.component.ts
  src/app/users/users-update/users-update.component.ts
Labels: in progress

#598 [WIP] 564 profile image crop
  package.json
  src/app/app.module.ts
  src/app/users/users-update/users-update.component.html
  src/app/users/users-update/users-update.component.ts
  src/app/users/users.module.ts
Labels: in progress

#614 [#613] Add meetup details on meetups.component.html (connect #613)
  src/app/meetups/meetups.component.html
  src/app/meetups/meetups.component.ts
Labels: in progress

#723 [#721] courses table Sort (connect #721)
  src/app/courses/courses.component.html
  src/app/courses/courses.component.ts
Labels: in progress

#717 [#704] trim filter to ignore white space
  src/app/courses/courses.component.ts
  src/app/feedback/feedback.component.ts
  src/app/meetups/meetups.component.ts
  src/app/resources/resources.component.ts
  src/app/shared/table-helpers.ts
  src/app/users/users.component.ts
Labels: in progress

#716 [#710] Resource Table Sort connects(#710)
  src/app/resources/resources.component.html
  src/app/resources/resources.component.ts
Labels: in progress

#715 [#713] added replaced ids in shelf(connects #713)
  src/app/resources/resources.component.ts
Labels: in progress

#699 [#675] Clear selceted checkbox on change page ( connects #675)
  src/app/courses/courses.component.html
  src/app/courses/courses.component.ts
  src/app/meetups/meetups.component.html
  src/app/meetups/meetups.component.ts
  src/app/resources/resources.component.html
  src/app/resources/resources.component.ts
  src/app/users/users.component.html
  src/app/users/users.component.ts
Labels: WIP, in progress

#692 styling profile image update fixes #634
  src/app/users/users-update/users-update.component.html
  src/styles.scss
Labels: in progress

#727 Update version
  package.json
Labels: in progress

#748 Fix loading dashboard info for non-admin (fixes #732)
  src/app/dashboard/dashboard.component.ts
Labels: in progress

#747 Center protocol environment variable (fixes #746)
  src/app/shared/couchdb.service.ts
  src/environments/environment.prod.ts
  src/environments/environment.test.ts
  src/environments/environment.ts
Labels: in progress

#745 [#744] Nation list from earth (connects #744)
  src/app/configuration/configuration.component.ts
Labels: in progress

#739 [#735] Add date in meetups mockups (connects #735)
  design/meetups/meetups-mockup.json
Labels: in progress

#601 [#476] a re-enabled user is nearly loosing all the old assigned roles
  src/app/users/users.component.html
  src/app/users/users.component.ts
Labels: in progress

#755 Troubleshooting in README (connects #590)
  README.md
Labels: in progress

#742 [#286] Enable multiple admin (connects #286)
  couchdb-setup.sh
  design/security-update/security-update.json
  src/app/users/users.component.html
  src/app/users/users.component.ts
Labels: in progress

#718 [#708] Update feedback list (connects #708)
  src/app/app.module.ts
  src/app/feedback/feedback.component.ts
  src/app/feedback/feedback.directive.ts
  src/app/feedback/feedback.service.ts
Labels: in progress, in review

#616 [#541] making learner readonly for nations (connects #541)
  design/nations/nation-validators.js
  design/nations/nation-validators.json
Labels: in progress

#643 [#640] user joined added while createing new user (connects #640)
  src/app/configuration/configuration.component.ts
  src/app/login/login-form.component.ts
Labels: in progress

#636 [#600] Shelf in user service (connects #600)
  src/app/courses/courses.component.ts
  src/app/dashboard/dashboard.component.ts
  src/app/meetups/meetups.service.ts
  src/app/resources/resources.component.html
  src/app/resources/resources.component.ts
  src/app/shared/auth-guard.service.ts
  src/app/shared/user.service.ts
  src/app/users/users.component.ts
Labels: in progress

#738 [#731] Profile update redirect dashboard (connects #731)
  src/app/users/users-update/users-update.component.ts
Labels: in progress, in review

#652 Build without QEMU Binary (fixes #651 #621)
  .travis.yml
  docker/db-init/crosscompile_db-init.sh
  docker/db-init/rpi-Dockerfile
  docker/planet/crosscompile_planet.sh
  docker/planet/rpi-Dockerfile
  docker/qemu/cross-build-end
  docker/qemu/cross-build-start
  docker/qemu/qemu-arm-static
  docker/qemu/resin-xbuild
  docker/qemu/sh.real
Labels: in review

#757 Update version
  package.json
Labels: in progress

#799 Travis "build fail" fix
  docker/db-init/crosscompile_db-init.sh
  docker/db-init/rpi-Dockerfile
  docker/planet/crosscompile_planet.sh
  docker/planet/rpi-Dockerfile
Labels: in progress

#786 [#771] Multiple role select (connects #771)
  src/app/users/users.component.html
  src/app/users/users.component.ts
  src/styles.scss
Labels: in progress

#785 [#772] Feedback status title (connects #772)
  src/app/feedback/feedback-view.component.html
  src/app/feedback/feedback-view.component.ts
  src/app/feedback/feedback.component.html
  src/app/feedback/feedback.component.ts
  src/app/feedback/feedback.directive.ts
Labels: in progress

#778 [#765] Empty card message with link (connects #765)
  src/app/dashboard/dashboard-tile.component.html
  src/app/dashboard/dashboard-tile.component.ts
  src/app/dashboard/dashboard-tile.scss
  src/app/dashboard/dashboard.component.ts
Labels: in progress

#783 [#775] Selected resources indication (connects #775)
  src/app/resources/resources.component.html
  src/app/resources/resources.component.ts
Labels: in progress

#760 [#759] Remove security of shelf (connects #759)
  design/security-update/security-update.json
Labels: in progress

#736 [#729] created date for nations & communities added (connects #729)
  src/app/configuration/configuration.component.ts
Labels: in progress

#780 [#777] Remove local url input field (connects #777)
  src/app/configuration/configuration.component.html
  src/app/configuration/configuration.component.ts
  src/app/shared/material.module.ts
Labels: in progress

#687 [#686] user view profile button (connects #686)
  src/app/users/users.component.html
Labels: in progress

#661 [#630] Add old password field (connects #630)
  src/app/shared/form-error-messages.component.ts
  src/app/users/users-profile/users-profile.component.ts
  src/app/validators/validator.service.ts
Labels: in progress

#798 [#797] runtime sent feedback success message (connects #797)
  src/app/feedback/feedback.directive.ts
Labels: in progress

#793 [#790] Notification item color change (connects #790)
  src/app/home/home.component.ts
  src/app/notifications/notifications.component.ts
  src/app/shared/user.service.ts
Labels: in progress

#792 [#768] change add library to mylibrary (connects #768)
  src/app/resources/resources.component.html
  src/app/resources/resources.component.ts
Labels: in progress

#696 [#693] Course add form style (connects #693)
  src/app/courses/add-courses/courses-add.scss
Labels: in progress

#801 Change user roles to leader or learner (connects #734)
  design/security-update/security-update.json
  src/app/users/users.component.ts
Labels: in progress
