Repository open-learning-exchange/planet, pull requests merged in 2018-10, with the labels that each got.

#2234 [#2228] meetup end date (connects #2228)
  src/app/meetups/add-meetups/meetups-add.component.ts
Labels: in progress

#2244 [#2211] resource view downalod button and detail view margin (connects #2211)
  src/app/resources/view-resources/resources-view.scss
Labels: in progress

#2243 [2193]-sorting-user-title (connects #2193)
  src/app/users/users.component.html
  src/app/users/users.component.ts
Labels: in progress

#2098 delay on resource load ondelete (connects #2087)
  src/app/shared/dialogs/dialogs-prompt.component.html
  src/app/shared/dialogs/dialogs-prompt.component.ts
Labels: in progress

#2209 [#2186] meetup end date empty (connects #2186)
  src/app/meetups/meetups.component.html
Labels: in progress

#2247 Update version
  package.json
Labels: in progress

#2272 Activity Log (1861 Paul's subbranch)
  couchdb-setup.sh
  design/activity_logs/activity_logs-design.js
  design/activity_logs/activity_logs-design.json
  design/login_activities/login_activities-design.js
  design/login_activities/login_activities-design.json
  design/ratings/ratings-design.js
  design/ratings/ratings-design.json
  design/resource_activities/resource_activities-design.js
  design/resource_activities/resource_activities-design.json
  design/users/users-design.js
  design/users/users-design.json
  src/app/activity-logs/activity-logs-report.component.html
  src/app/activity-logs/activity-logs-report.component.ts
  src/app/activity-logs/activity-logs.component.html
  src/app/activity-logs/activity-logs.component.ts
  src/app/activity-logs/activity.service.ts
  src/app/manager-dashboard/manager-sync.component.ts
  src/app/shared/couchdb.service.ts
Labels: in progress

#2258 2229-change user creation message (connects #2229)
  src/app/login/login-form.component.ts
Labels: in progress

#2267 Make new user's notification New member
  src/app/login/login-form.component.ts
Labels: in progress

#2206 [#2184] user back button (connects #2184)
  src/app/users/users.component.ts
Labels: in progress

#1863 [#1861] Add log service (connects #1861)
  .travis.yml
  couchdb-setup.sh
  design/security-update/security-update.json
  design/users/_auth.json
  src/app/configuration/configuration.component.ts
  src/app/configuration/configuration.service.ts
  src/app/courses/courses.component.html
  src/app/courses/view-courses/courses-view.component.html
  src/app/feedback/feedback.directive.ts
  src/app/login/login-form.component.ts
  src/app/manager-dashboard/manager-dashboard.component.html
  src/app/manager-dashboard/manager-dashboard.component.ts
  src/app/manager-dashboard/manager-dashboard.module.ts
  src/app/manager-dashboard/manager-sync.component.ts
  src/app/manager-dashboard/manager.service.ts
  src/app/manager-dashboard/manger-dashboard-router.module.ts
  src/app/manager-dashboard/reports/reports-detail.component.html
  src/app/manager-dashboard/reports/reports-detail.component.ts
  src/app/manager-dashboard/reports/reports.component.html
  src/app/manager-dashboard/reports/reports.component.ts
  src/app/manager-dashboard/reports/reports.service.ts
  src/app/resources/resources.component.html
  src/app/resources/view-resources/resources-view.component.html
  src/app/resources/view-resources/resources-view.component.ts
  src/app/shared/couchdb.service.ts
  src/app/shared/forms/planet-rating.component.ts
  src/app/shared/user.service.ts
  src/app/upgrade/upgrade.component.ts
Labels: WIP, in progress

#2203 [#2160] margin added(connects #2160)
  src/app/teams/teams-view.component.html
  src/app/teams/teams-view.scss
Labels: in progress

#2266 [#2251] your progress on nation (connects #2251)
  src/app/courses/courses.component.html
  src/app/courses/view-courses/courses-view.component.html
Labels: in progress

#2242 [#2161]mark as read added(connects #2161)
  src/app/notifications/notifications.component.html
  src/app/notifications/notifications.component.ts
Labels: in progress

#2230 2218 - column head value mismatch (connects #2218)
  src/app/feedback/feedback.component.html
Labels: in progress

#2231 [#2222] expand the feedback title edit field (connects #2222)
  src/app/feedback/feedback-view.component.html
  src/app/feedback/feedback-view.scss
Labels: in progress

#2137 2052-feedback status and priority list color
  src/app/feedback/feedback.component.html
Labels: in progress

#2089 Add open new tab in resource view(connects #2073)
  src/app/resources/view-resources/resources-view.component.html
Labels: in progress

#2074 Record survey : in case of multiple choice multi select question padding should be added at bottom(connects #2069)
  src/app/exams/exams-view.scss
Labels: in progress

#2273 Update version
  package.json
Labels: in progress

#2275 Clean up unused variables
  src/app/manager-dashboard/reports/reports-detail.component.ts
  src/app/manager-dashboard/reports/reports.component.ts
Labels: in progress

#2172 Speed up resources list in course step (fixes #2131)
  src/app/community/community.component.ts
  src/app/courses/add-courses/courses-step.component.ts
  src/app/courses/courses.component.ts
  src/app/manager-dashboard/manager-dashboard.component.ts
  src/app/meetups/view-meetups/meetups-view.component.ts
  src/app/resources/resources.component.ts
  src/app/resources/resources.service.ts
  src/app/shared/dialogs/dialogs-list.service.ts
  src/app/shared/state.service.ts
  src/app/surveys/surveys.component.ts
  src/app/teams/teams-view.component.ts
Labels: in progress, priority

#2290 Fix grading exam (fixes #2262) (fixes #2279)
  src/app/exams/exams-view.component.html
  src/app/exams/exams-view.component.ts
Labels: in progress, priority

#2134 Check _changes to always store up to date planet configuration (connects #2068)
  src/app/configuration/configuration.component.ts
  src/app/configuration/configuration.service.ts
  src/app/courses/add-courses/courses-add.component.ts
  src/app/courses/courses.component.html
  src/app/courses/courses.component.ts
  src/app/feedback/feedback.component.ts
  src/app/feedback/feedback.directive.ts
  src/app/home/home.component.ts
  src/app/login/login-form.component.ts
  src/app/manager-dashboard/manager-dashboard.component.html
  src/app/manager-dashboard/manager-dashboard.component.ts
  src/app/manager-dashboard/manager-sync.component.ts
  src/app/manager-dashboard/manager.service.ts
  src/app/manager-dashboard/reports/reports-detail.component.ts
  src/app/manager-dashboard/reports/reports.component.ts
  src/app/meetups/meetups.component.ts
  src/app/meetups/view-meetups/meetups-view.component.ts
  src/app/resources/resources-add.component.ts
  src/app/resources/resources.component.html
  src/app/resources/resources.component.ts
  src/app/resources/resources.service.ts
  src/app/resources/view-resources/resources-view.component.ts
  src/app/resources/view-resources/resources-viewer.component.ts
  src/app/shared/auth-guard.service.ts
  src/app/shared/couchdb.service.ts
  src/app/shared/dialogs/change-password.directive.ts
  src/app/shared/forms/planet-rating.component.ts
  src/app/shared/forms/rating.service.ts
  src/app/shared/state.service.ts
  src/app/shared/sync.service.ts
  src/app/shared/user.service.ts
  src/app/surveys/surveys.component.ts
  src/app/upgrade/upgrade.component.ts
  src/app/users/users-update/users-update.component.ts
  src/app/users/users.component.ts
Labels: in progress, priority

#2295 [#2111] delete meetup by index instead of first item (connects #2111)
  src/app/meetups/meetups.service.ts
Labels: in progress

#2291 [#2276] your progress course (connects #2276)
  src/app/courses/courses.component.html
  src/app/courses/view-courses/courses-view.component.html
Labels: in progress

#2285 [#2156] Pass count data for resources into dialog prompt
  src/app/resources/resources.component.ts
  src/app/shared/dialogs/dialogs-prompt.component.html
Labels: in progress

#2296 Update version
  package.json
Labels: in progress

#2299 Add reporting fields to courses_progress and submissions (fixes #2298)
  src/app/courses/courses.service.ts
  src/app/submissions/submissions.service.ts
Labels: in progress

#2310 In reports change labels to Members
  src/app/manager-dashboard/reports/reports-detail.component.html
  src/app/manager-dashboard/reports/reports.component.html
Labels: in progress, priority

#2311 Fix multiple users rating resources and courses
  src/app/shared/forms/rating.service.ts
Labels: in progress, priority

#2315 [2281] Manager reports link to details
  src/app/manager-dashboard/reports/reports.component.html
Labels: in progress

#2316 Update version
  package.json
Labels: in progress

#2317 [#2301] fix listing parent resources error(connects #2301)
  src/app/shared/state.service.ts
Labels: in progress

#2314 Filter satellite user from report
  src/app/manager-dashboard/reports/reports.service.ts
Labels: in progress

#2318 [#2257] spinner on add resources (connects #2257)
  src/app/courses/add-courses/courses-step.component.html
  src/app/courses/add-courses/courses-step.component.ts
Labels: in progress

#2332 Exclude blank data from report
  src/app/manager-dashboard/reports/reports.service.ts
Labels: in progress

#2329 change toggle button color (fixes #2325)
  src/app/_variables.scss
  src/planet-mat-theme.scss
Labels: in progress

#2289 [#2109] no survey found (connects #2109)
  src/app/surveys/surveys.component.html
  src/app/surveys/surveys.component.ts
Labels: in progress

#2292 [#2263] fix planet-markdown-textbox does not show error on submit (connects#2263)
  src/app/shared/forms/planet-markdown-textbox.component.ts
Labels: in progress

#2333 Update version
  package.json
Labels: in progress

#2338 [#2337] User total report (connects #2337)
  src/app/manager-dashboard/reports/reports-detail.component.ts
  src/app/manager-dashboard/reports/reports.service.ts
Labels: in progress

#2341 Fix ReportsDetailComponent initialization
  src/app/manager-dashboard/reports/reports-detail.component.ts
  src/app/manager-dashboard/reports/reports.service.ts
Labels: in progress

#2320 Updated exam title for add and update (fixes #2249)
  src/app/exams/exams-add.component.html
  src/app/exams/exams-add.component.ts
Labels: in progress

#2342 Course with resource and exam (connects #2335)
  src/app/courses/courses.component.ts
  src/app/manager-dashboard/manager-dashboard.component.html
Labels: in progress

#2340 Make reports scroll within view-container (connects #2282)
  src/app/manager-dashboard/reports/reports-detail.component.ts
  src/styles.scss
Labels: in progress

#2346 Update version
  package.json
Labels: in progress

#2358 New Crowdin translations
  src/i18n/messages.afr.xlf
  src/i18n/messages.ara.xlf
  src/i18n/messages.deu.xlf
  src/i18n/messages.eng.xlf
  src/i18n/messages.fra.xlf
  src/i18n/messages.hin.xlf
  src/i18n/messages.ind.xlf
  src/i18n/messages.ita.xlf
  src/i18n/messages.mlg.xlf
  src/i18n/messages.nep.xlf
  src/i18n/messages.por.xlf
  src/i18n/messages.rus.xlf
  src/i18n/messages.som.xlf
  src/i18n/messages.spa.xlf
  src/i18n/messages.swa.xlf
  src/i18n/messages.tam.xlf
  src/i18n/messages.tur.xlf
  src/i18n/messages.vie.xlf
  src/i18n/messages.zho.xlf
  src/i18n/messages.zul.xlf
Labels: in progress

#2360 i18n updates for classic navbar
  src/app/exams/exams-add.component.html
  src/app/home/home-classic.component.html
  src/app/manager-dashboard/manager-dashboard.component.html
  src/app/manager-dashboard/reports/reports-detail.component.html
  src/app/shared/forms/form-error-messages.component.ts
  src/i18n/messages.afr.xlf
  src/i18n/messages.ara.xlf
  src/i18n/messages.deu.xlf
  src/i18n/messages.eng.xlf
  src/i18n/messages.fra.xlf
  src/i18n/messages.hin.xlf
  src/i18n/messages.ind.xlf
  src/i18n/messages.ita.xlf
  src/i18n/messages.mlg.xlf
  src/i18n/messages.nep.xlf
  src/i18n/messages.por.xlf
  src/i18n/messages.rus.xlf
  src/i18n/messages.som.xlf
  src/i18n/messages.spa.xlf
  src/i18n/messages.swa.xlf
  src/i18n/messages.tam.xlf
  src/i18n/messages.tur.xlf
  src/i18n/messages.vie.xlf
  src/i18n/messages.xlf
  src/i18n/messages.zho.xlf
  src/i18n/messages.zul.xlf
Labels: in progress

#2357 Fix planet setup configuration error
  src/app/shared/state.service.ts
Labels: in progress

#2365 [#2305] Resource description in detail page (connects #2305)
  src/app/resources/view-resources/resources-view.component.html
Labels: in progress

#2359 [#2352] admin activities (connects #2352)
  src/app/manager-dashboard/manager-dashboard.component.ts
  src/app/manager-dashboard/reports/reports.service.ts
Labels: in progress

#2383 [#2356] course step resource switch (connects #2356)
  src/app/courses/step-view-courses/courses-step-view.component.html
  src/app/resources/resources.service.ts
  src/app/resources/view-resources/resources-viewer.component.ts
Labels: in progress

#2319 [#2308] resource count (connects #2308)
  src/app/resources/view-resources/resources-view.component.ts
  src/app/resources/view-resources/resources-viewer.component.ts
Labels: in progress

#1818 Truncating the list view of text throughout planet(fixes #1787)
  src/app/courses/courses.component.html
  src/styles.scss
Labels: in progress

#2388 Change the layout for the button (connects #2323)
  src/app/resources/view-resources/resources-view.component.html
Labels: in progress

#2382 [#2351] Notification message while creating the new resources (connects #2351)
  src/app/resources/resources-add.component.ts
Labels: in progress

#2386 [#2379] ResrouceAdd scroll (connects #2379)
  src/app/resources/resources-add.component.html
Labels: in progress

#2387 [#2368] Clicking add step while editing step changes to edit new step (connects #2368)
  src/app/courses/add-courses/courses-add.component.ts
  src/app/courses/add-courses/courses-step.component.html
  src/app/shared/forms/planet-step-list.component.html
Labels: in progress

#2385 Remove undefined error msg
  src/app/shared/forms/form-error-messages.component.ts
Labels: in progress

#2347 [#2328] sending survey prevent password(connects #2328)
  src/app/manager-dashboard/manager-sync.component.ts
  src/app/shared/dialogs/dialogs-list.component.ts
  src/app/shared/dialogs/dialogs-list.service.ts
  src/app/shared/user.service.ts
  src/app/surveys/surveys.component.ts
Labels: WIP, in progress

#2198 [#2164] duplicate configuration (connects #2164)
  src/app/configuration/configuration.service.ts
Labels: in progress

#1950 Update profile layout fix (fixes #1881)
  src/app/users/users-update/users-update.component.html
Labels: in progress

#2389 Add spacing between Update Survey (connects #2377)
  src/app/exams/exams-add.component.html
Labels: in progress

#2392 Fix scrolling for markdown editors
  src/app/shared/forms/planet-markdown-textbox.scss
Labels: in progress, priority

#2394 [#2380] course-step-title in progress is set to step_no (connects #2380)
  src/app/courses/progress-courses/courses-progress.component.html
Labels: in progress

#2395 Update version
  package.json
Labels: in progress

#2411 Survey/Exam submission color codes (fixes #2404)
  src/app/submissions/submissions.component.html
Labels: in progress

#2408 Report label style adjustment (fixes #2373)
  src/app/manager-dashboard/reports/reports-detail.component.html
  src/app/manager-dashboard/reports/reports-detail.component.ts
  src/app/manager-dashboard/reports/reports-detail.scss
Labels: in progress

#2393 No attachment hide resource button (fixes #2304)
  src/app/courses/view-courses/courses-view.component.ts
Labels: in progress

#2412 Update version
  package.json
Labels: in progress

#2422 ole/stretch64 0.5.3
  Vagrantfile
Labels: in progress
