Repository open-learning-exchange/planet, pull requests merged in 2018-05, with the labels that each got.

#802 Lint fixes
  src/app/dashboard/dashboard-tile.component.ts
  src/app/dashboard/dashboard.component.html
  src/app/dashboard/dashboard.component.ts
Labels: in progress

#725 Make description in add resources wider (fixes #702)
  src/app/resources/resources-add.component.html
  src/styles.scss
Labels: in progress

#796 [#795] Start date should not be before current date (connects #795)
  src/app/meetups/add-meetups/meetups-add.component.ts
  src/app/shared/form-error-messages.component.ts
  src/app/validators/custom-validators.ts
Labels: in progress

#823 [#809] Courses add template media queries (connects #809)
  src/app/_variables.scss
  src/app/courses/add-courses/courses-add.scss
Labels: in progress

#825 [#824] lint warning (connects #824)
  git-hooks/pre-push
  package.json
  src/app/configuration/configuration.component.ts
  src/app/feedback/feedback.directive.ts
  src/app/login/login-form.component.ts
  src/app/resources/rating-resources/resources-rating.component.ts
  src/app/resources/resources.service.ts
  src/app/shared/dialogs/dialogs-list.service.ts
  src/app/shared/table-helpers.ts
Labels: in progress

#818 [#811] Confirmation message on domain change (connects #811)
  src/app/configuration/configuration.component.html
  src/app/configuration/configuration.component.ts
Labels: in progress

#690 [#668] partial course step view (connects #668)
  src/app/courses/courses-router.module.ts
  src/app/courses/courses.module.ts
  src/app/courses/courses.service.ts
  src/app/courses/step-view-courses/courses-step-view.component.html
  src/app/courses/step-view-courses/courses-step-view.component.ts
  src/app/courses/view-courses/courses-view.component.html
  src/app/courses/view-courses/courses-view.component.ts
Labels: in progress

#822 [#813] Course step to scroll separately (connects #813)
  src/app/courses/add-courses/courses-add.component.html
  src/app/courses/add-courses/courses-add.scss
  src/styles.scss
Labels: in progress

#820 Multiarch support for planet
  .travis.yml
  .travis/deploy_rpi.sh
  .travis/travis_utils.sh
Labels: in progress

#849 [#840] Introduce new variable for configuration confirm (connects #840)
  src/app/configuration/configuration.component.html
  src/app/configuration/configuration.component.ts
Labels: in progress

#679 Add simple exam to course steps
  .travis.yml
  couchdb-setup.sh
  src/app/courses/add-courses/courses-add.component.html
  src/app/courses/add-courses/courses-add.component.ts
  src/app/courses/add-courses/courses-step.component.html
  src/app/courses/add-courses/courses-step.component.ts
  src/app/courses/courses-router.module.ts
  src/app/courses/courses.module.ts
  src/app/courses/courses.service.ts
  src/app/exams/exams-add.component.html
  src/app/exams/exams-add.component.ts
  src/app/exams/exams-question.component.html
  src/app/exams/exams-question.component.ts
Labels: in progress

#814 [#807] Increase session time to 20 min (connects #807)
  couchdb-setup.sh
Labels: in progress

#622 [#563] Update dashboard view (connects #563)
  src/app/_variables.scss
  src/app/dashboard/dashboard-tile.component.html
  src/app/dashboard/dashboard-tile.component.ts
  src/app/dashboard/dashboard-tile.scss
  src/app/dashboard/dashboard.component.html
  src/app/dashboard/dashboard.component.ts
  src/app/dashboard/dashboard.scss
Labels: in progress

#856 Update version
  package.json
Labels: in progress

#865 [#852] Header logo and font (connects #852)
  src/app/home/home.component.html
  src/app/home/home.scss
  src/app/login/login.scss
  src/styles.scss
Labels: in progress

#863 [#844] Course add submit button at top (connects #844)
  src/app/courses/add-courses/courses-add.component.html
Labels: in progress

#864 [#834] Delecting items from course fix (connects #834)
  src/app/courses/courses.component.ts
Labels: in progress, in review

#854 [#841] Admin configuration should not be available once done (connects #841)
  src/app/configuration/configuration-guard.service.ts
  src/app/login/login-router.module.ts
  src/app/login/login.module.ts
Labels: in progress, in review

#860 [#691] Google Analytics added for page view tracking
  src/app/app.component.ts
  src/index.html
Labels: in progress

#861 Fix versioned multiarch Logic
  .travis/travis_utils.sh
Labels: in progress

#874 add docker-compose to Vagrantfile
  Vagrantfile
Labels: in progress

#870 Remove reply from Feedback component (connects #791)
  src/app/feedback/feedback.component.html
  src/app/feedback/feedback.component.ts
Labels: in progress

#654 [#653] refactor dialogs-form.component.html (connects #653)
  src/app/shared/dialogs/dialogs-form.component.html
Labels: in progress

#887 [#884] User site button icon before text (connects #884)
  src/app/users/users.component.html
Labels: in progress

#700 [#694] course step reorder (connects #694)
  src/app/courses/add-courses/courses-add.component.ts
  src/app/courses/add-courses/courses-step.component.html
  src/app/courses/add-courses/courses-step.component.ts
Labels: in progress

#756 [#743] User should not see self in user list (connects #743)
  src/app/users/users.component.ts
Labels: in progress

#764 [#763] script to make user db public (connects #763)
  couchdb-setup.sh
Labels: in progress

#779 [#770] Add multilevel filter specific fields (connects #770)
  src/app/shared/table-helpers.ts
  src/app/users/users.component.ts
Labels: in progress

#784 [#773] Selected users indication (connects #773)
  src/app/users/users.component.html
  src/app/users/users.component.ts
Labels: in progress

#817 [#810] Default title for feedback (connects #810)
  src/app/feedback/feedback.directive.ts
Labels: in progress, in review

#800 [#766] Fix Added items ends up as last item in list views (connects #766)
  design/courses/courses-mockup.json
  design/meetups/meetups-mockup.json
  src/app/courses/add-courses/courses-add.component.html
  src/app/courses/add-courses/courses-add.component.ts
  src/app/courses/courses.component.ts
  src/app/meetups/add-meetups/meetups-add.component.html
  src/app/meetups/meetups.component.ts
  src/app/resources/resources.component.ts
Labels: in progress

#815 [#805] View details of community/nation (connects #805)
  src/app/manager-dashboard/manager-dashboard.component.ts
  src/app/nation/nation.component.html
  src/app/nation/nation.component.ts
  src/app/shared/dialogs/dialogs-view.component.html
  src/app/shared/dialogs/dialogs-view.component.ts
Labels: in progress

#889 [#883] Users site button aligned (connects #883)
  src/app/users/users.component.html
  src/styles.scss
Labels: in progress

#888 [#886] Course steps in mock data (connects #886)
  design/courses/courses-mockup.json
Labels: in progress

#879 [#868] Hide delete for admin (connects #868)
  src/app/users/users.component.html
Labels: in progress

#926 [#917] Update validator to check domain (connects #917)
  src/app/configuration/configuration.component.html
  src/app/configuration/configuration.component.ts
  src/app/validators/validator.service.ts
Labels: in progress

#900 [#895] Feedback scrolls to oldest message when replying (connect #895)
  src/app/feedback/feedback-view.component.ts
Labels: in progress

#892 [#875] Function to get dynamic resource link (connects #875)
  src/app/resources/resources.component.ts
Labels: in progress

#898 [#858] Course resource select improvement (connects #858)
  src/app/courses/add-courses/courses-step.component.ts
  src/app/shared/dialogs/dialogs-list.component.html
  src/app/shared/dialogs/dialogs-list.component.ts
Labels: in progress, in review

#850 [#831] Custom validator for positive number (connects #831)
  src/app/courses/add-courses/courses-add.component.ts
  src/app/shared/form-error-messages.component.ts
  src/app/validators/custom-validators.ts
Labels: Rebased, in progress

#855 [#837] Delete request, parent and user (connects #837)
  src/app/community/community.component.ts
  src/app/configuration/configuration.component.ts
  src/app/nation/nation.component.ts
Labels: Rebased, in progress

#973 [#962] Course add resource search for number (connects #962)
  src/app/courses/add-courses/courses-step.component.ts
  src/app/shared/dialogs/dialogs-list.component.ts
Labels: in progress

#969 [#967] Removed required from textarea in course step (connects #967)
  src/app/courses/add-courses/courses-step.component.html
Labels: in progress

#821 [#812] Error changing password message when change is successful (connects #812 )
  src/app/users/users-profile/users-profile.component.ts
Labels: Rebased, in progress, in review

#705 [#701] Navbar selection and animation (connects #701)
  src/app/home/home.component.html
  src/app/home/home.module.ts
  src/app/home/home.scss
  src/app/home/pulsate-icon.directive.ts
Labels: Rebased, in progress

#1009 [#989] Added take test and view resource buttons on course step view (connects #989)
  src/app/courses/view-courses/courses-view.component.html
  src/app/courses/view-courses/courses-view.component.ts
Labels: in progress, in review

#1008 [#998] Parent online status (connects #998)
  src/app/login/login.component.html
  src/app/login/login.component.ts
Labels: in progress

#1007 [#1004] Notification for community request (connects #1004)
  src/app/configuration/configuration.component.ts
  src/app/home/home.component.ts
  src/app/notifications/notifications.component.ts
Labels: in progress

#1066 [#1049] Replicator for feedback sync (connects #1049)
  src/app/configuration/configuration.component.ts
Labels: WIP

#637 [#606] Request member to join the meetup (connect #606)
  src/app/courses/add-courses/courses-step.component.ts
  src/app/meetups/meetups.module.ts
  src/app/meetups/meetups.service.ts
  src/app/meetups/view-meetups/meetups-view.component.html
  src/app/meetups/view-meetups/meetups-view.component.ts
  src/app/shared/dialogs/dialogs-list.component.html
  src/app/shared/dialogs/dialogs-list.component.ts
  src/app/shared/dialogs/dialogs-list.service.ts
Labels: Rebased

#1071 [#1044] Resume exam from course view (connects #1044)
  src/app/courses/view-courses/courses-view.component.html
  src/app/courses/view-courses/courses-view.component.ts
Labels: in review

#754 [#750] Members joined on meetup (connects #750)
  src/app/meetups/view-meetups/meetups-view.component.html
  src/app/meetups/view-meetups/meetups-view.component.ts
  src/app/meetups/view-meetups/meetups-view.scss
Labels: Rebased, in progress

#1024 Take exam to Continue Exam if not first step (connects #1023)
  src/app/courses/step-view-courses/courses-step-view.component.html
Labels: in progress

#971 [#936] List of Languages (connects #936)
  src/app/users/users-update/users-update.component.html
  src/app/users/users-update/users-update.component.ts
Labels: in progress

#970 [#966] Hide source for community in feedback view (connects #966)
  src/app/feedback/feedback.component.ts
Labels: in progress

#924 [#869] Update shelf in table without clearing selection (connect #869)
  src/app/courses/courses.component.ts
  src/app/meetups/meetups.component.html
  src/app/meetups/meetups.component.ts
  src/app/resources/resources.component.ts
Labels: in progress

#1108 [#1098] No service in template: meetups.component.html (connect #1098)
  src/app/meetups/meetups.component.html
  src/app/meetups/meetups.component.ts
  src/app/meetups/view-meetups/meetups-view.component.ts
Labels: in progress

#1110 xi18n
  src/i18n/messages.xlf
Labels: in progress

#925 [#845] Multiple resources in course step(connects #845)
  src/app/courses/add-courses/courses-add.component.ts
  src/app/courses/add-courses/courses-step.component.html
  src/app/courses/add-courses/courses-step.component.ts
  src/app/courses/step-view-courses/courses-step-view.component.html
  src/app/courses/step-view-courses/courses-step-view.component.ts
  src/app/shared/dialogs/dialogs-list.component.html
  src/app/shared/dialogs/dialogs-list.component.ts
Labels: in progress

#1104 [#1088] immediate fix for replicator failing (connects #1088)
  src/app/configuration/configuration.component.ts
Labels: in progress

#1072 [#955] Changing nation trigger unique planet code (connects #955)
  src/app/configuration/configuration.component.html
  src/app/configuration/configuration.component.ts
Labels: in review

#1125 [#1119] Courses Menu adjusted (#1119)
  src/app/courses/courses.component.html
Labels: in progress

#1128 Rewrites debug without new observable (connects #1122)
  src/app/debug-operator.ts
Labels: in progress

#1085 [#1062] Added exam attempt number in step view (connects #1062)
  src/app/courses/courses.service.ts
  src/app/courses/step-view-courses/courses-step-view.component.html
  src/app/courses/step-view-courses/courses-step-view.component.ts
  src/app/courses/view-courses/courses-view.component.ts
Labels: in review

#1164 [#1162] 404 should link back to app (connects #1162）
  src/app/page-not-found/page-not-found.component.html
Labels: in progress

#1177 [#1170] Multiple deleting courses and meetups fix (connects #1170)
  src/app/courses/courses.component.ts
  src/app/meetups/meetups.component.ts
Labels: in progress

#1147 [#1145] Fetch request data (connects #1145)
  src/app/community/community.component.ts
Labels: in progress

#1087 [#950] Delete community in dev environment (connects #950)
  src/app/manager-dashboard/manager-dashboard.component.ts
Labels: in review

#1150 [#1139] Resource selection after delection doc fix (connects #1139)
  src/app/courses/courses.component.ts
  src/app/meetups/meetups.component.ts
  src/app/resources/resources.component.ts
  src/app/users/users.component.html
  src/app/users/users.component.ts
Labels: in progress

#1148 [#1141] Added filter and sorting in request list (connects #1141)
  couchdb-setup.sh
  src/app/community/community.component.html
  src/app/community/community.component.ts
Labels: in progress

#1026 [#1003] Allow course manage by either course creator or by admin only (connects #1003)
  src/app/courses/add-courses/courses-add.component.ts
  src/app/courses/courses.component.html
  src/app/courses/courses.component.ts
Labels: in review

#1105 [#1100] Feedback overview sorted by time (connects #1100)
  couchdb-setup.sh
  src/app/feedback/feedback.component.html
  src/app/feedback/feedback.component.ts
Labels: in progress

#1185 Update version
  package.json
Labels: in progress

#1187 [#1186] Back button of feedback page redirecting to access restricted page (connect #1186)
  src/app/feedback/feedback.component.html
  src/app/feedback/feedback.component.ts
Labels: in progress
