Repository open-learning-exchange/planet, pull requests merged in 2018-11, with the labels that each got.

#2199 [#2185] graded stop from complete in survey(connects #2185)
  src/app/submissions/submissions.service.ts
Labels: in progress

#2413 [2403] at is removed for empty location:(connects #2403)
  src/app/meetups/view-meetups/meetups-view.component.ts
Labels: in progress

#2429 Add level properity and spacing in resource details
  src/app/resources/view-resources/resources-view.component.html
Labels: in progress

#2434 Added long answer option to exams/courses
  src/app/exams/exams-question.component.html
  src/app/exams/exams-view.component.html
Labels: in progress

#2431 [#2426] member search problem fixed
  src/app/users/users.component.ts
Labels: in progress

#2433 Cleaner form for exam questions
  src/app/courses/add-courses/courses-step.component.html
  src/app/courses/add-courses/courses-step.component.ts
  src/app/exams/exams-add.component.html
  src/app/exams/exams-add.component.ts
  src/app/exams/exams-question.component.html
  src/app/exams/exams-question.component.ts
  src/app/exams/exams-view.component.html
  src/app/shared/forms/planet-step-list.component.ts
Labels: in progress

#2409 Vagrant for production
  Vagrantfile
  git-hooks/pre-push
  package.json
Labels: in progress

#2436 Update version
  package.json
Labels: in progress

#2428 [#2376] date sorting in feedback list (connects #2376)
  src/app/feedback/feedback.component.ts
  src/app/resources/resources.component.ts
Labels: in progress

#2443 Fixed survey console courseTitle error
  src/app/exams/exams-add.component.ts
Labels: in progress

#2450 Update version
  package.json
Labels: in progress

#2455 Fix reports list and manager dashboard table
  src/app/manager-dashboard/manager-dashboard.component.ts
  src/app/manager-dashboard/reports/reports.component.ts
  src/app/manager-dashboard/reports/reports.service.ts
Labels: in progress

#2448 [2437] overflow-removed(connects #2437)
  src/app/exams/exams-add.scss
Labels: in progress

#2456 Control months displayed in reports
  src/app/manager-dashboard/reports/reports-detail.component.ts
Labels: in progress

#2446 smooth port transition
  Vagrantfile
Labels: in progress

#2462 Save course after adding exam
  src/app/courses/add-courses/courses-add.component.ts
Labels: in progress

#2459 Fix resources view layout
  src/app/resources/view-resources/resources-view.component.html
  src/app/resources/view-resources/resources-view.scss
Labels: in progress

#2461 Update text of course
  src/app/courses/courses.component.html
  src/app/courses/courses.service.ts
  src/app/courses/view-courses/courses-view.component.html
Labels: in progress

#2463 Reports List: Filter out not accepted communities and fix pagination and sort
  src/app/manager-dashboard/reports/reports.component.ts
Labels: in progress

#2468 Fix child total resources & courses
  .travis.yml
  couchdb-setup.sh
  src/app/manager-dashboard/manager-sync.component.ts
  src/app/manager-dashboard/reports/reports-detail.component.ts
  src/app/manager-dashboard/reports/reports.service.ts
Labels: in progress

#2464 Increase default page size on lists
  src/app/community/community.component.html
  src/app/courses/courses.component.html
  src/app/feedback/feedback.component.html
  src/app/manager-dashboard/reports/reports.component.html
  src/app/meetups/meetups.component.html
  src/app/notifications/notifications.component.html
  src/app/resources/resources.component.html
  src/app/submissions/submissions.component.html
  src/app/teams/teams.component.html
  src/app/users/users.component.html
Labels: in progress

#2449 Improve message after creating or updating a course or a meetup
  src/app/courses/add-courses/courses-add.component.ts
  src/app/meetups/add-meetups/meetups-add.component.ts
Labels: in progress

#2430 [#2417] disable button if already enrolled in a course (connects # 2417)
  src/app/courses/courses.component.html
  src/app/courses/courses.component.ts
Labels: in progress

#2473 Update version
  package.json
Labels: in progress

#2245 Code of conduct
  CODE_OF_CONDUCT.md
  README.md
Labels: in progress, pending, vote needed

#2482 [2438] up down buttons fixed(connects #2438)
  src/app/shared/forms/planet-step-list.component.ts
Labels: in progress

#2487 2481 team create date (connects #2481)
  src/app/teams/teams.component.html
  src/app/teams/teams.component.ts
  src/app/teams/teams.service.ts
Labels: in progress

#2478 Load resources on login
  src/app/shared/auth-guard.service.ts
  src/app/shared/state.service.ts
Labels: in progress

#2480 Vbguest autoupdate false
  Vagrantfile
Labels: in progress

#2484 Disabling delete file if no file(fixes #2086)
  src/app/resources/resources-add.component.html
  src/app/resources/resources-add.component.ts
Labels: in progress

#2488 Update version
  package.json
Labels: in progress

#2472 Changed background color of the login button (fixes #2467)
  src/app/_variables.scss
  src/app/login/login-form.component.html
  src/app/login/login.scss
  src/planet-mat-theme.scss
Labels: in progress

#2495 Optimising delete file visibility(fixes #2493)
  src/app/resources/resources-add.component.html
Labels: in progress

#2466 Full screen toggle (fixes #2420)
  src/app/home/home.scss
  src/app/shared/forms/planet-markdown-textbox.scss
Labels: in progress

#2519 Added required to start day field (fixes #2492)
  src/app/meetups/add-meetups/meetups-add.component.html
Labels: in progress

#2517 [#2427] upgrade log screen width (connects #2427)
  src/app/upgrade/upgrade.scss
Labels: in progress

#2479 Add dialog for labels (connects #2502)
  src/app/resources/resources-add.component.html
  src/app/resources/resources.component.html
  src/app/shared/forms/planet-forms.module.ts
  src/app/shared/forms/planet-tag-input-dialog.component.html
  src/app/shared/forms/planet-tag-input.component.html
  src/app/shared/forms/planet-tag-input.component.ts
  src/app/shared/forms/planet-tag-input.scss
  src/styles.scss
Labels: in progress, priority

#2520 Update version
  package.json
Labels: in progress

#2528 Fix expression change error in resource view
  src/app/resources/view-resources/resources-view.component.html
  src/app/resources/view-resources/resources-viewer.component.ts
Labels: in progress

#2531 Show parent labels when viewing parent (connects #2523)
  src/app/resources/resources.component.html
  src/app/shared/forms/planet-tag-input.component.ts
  src/app/shared/forms/tags.service.ts
Labels: in progress

#2530 Fix console error on resources page (fixes #2278)
  src/app/courses/courses.service.ts
Labels: in progress

#2534 Update Vagrantfile for new template
  Vagrantfile
Labels: in progress

#2535 Changing lower to Upper
  src/app/resources/resources-add.component.html
Labels: in progress

#2511 Upgrade to Angular 7 (fixes #2010)
  Vagrantfile
  package.json
  src/app/courses/courses.component.ts
  src/app/home/home.component.html
  src/app/home/home.component.ts
  src/app/home/home.scss
Labels: in progress

#2529 2527 team notification update (connects #2527)
  src/app/teams/teams.service.ts
Labels: in progress

#2537 Update version
  package.json
Labels: in progress

#2551 [#2539] member notify (connects #2539)
  src/app/teams/teams-view.component.ts
  src/app/teams/teams.service.ts
Labels: in progress

#2533 [#2526] submission send survey update response (connects #2526)
  src/app/exams/exams-view.component.ts
Labels: in progress

#2516 Report Detail null or empty value (fixes #2494)
  src/app/manager-dashboard/reports/reports-detail.component.html
Labels: in progress

#2548 Fix first logout not working (fixes #2425)
  src/app/app.component.ts
  src/app/login/login-form.component.ts
  src/app/shared/auth-guard.service.ts
Labels: in progress

#2513 Courses click to step from course progress bar (fixes #2421)
  src/app/courses/progress-courses/courses-progress-bar.component.html
  src/app/courses/progress-courses/courses-progress-bar.component.ts
Labels: in progress

#2557 Update version
  package.json
Labels: in progress

#2586 Fix progress leader view
  src/app/courses/progress-courses/courses-progress-leader.component.ts
Labels: in progress

#2571 Sort rate in resources mat table
  src/app/resources/resources.component.ts
Labels: in progress

#2579 [#2538] Change rating pop-up placeholder
  src/app/shared/forms/planet-rating.component.ts
Labels: in progress

#2575 [#2567] parent meetup view (connects #2567)
  src/app/meetups/view-meetups/meetups-view.component.html
Labels: in progress

#2576 [2552] correct choice initialized (connects #2552)
  src/app/exams/exams-question.component.ts
Labels: in progress

#2577 Send course to child (connects #2549)
  src/app/courses/courses.component.html
  src/app/courses/courses.component.ts
Labels: in progress

#2582 Courses progress database change (fixes #2554)
  src/app/courses/courses.service.ts
  src/app/courses/progress-courses/courses-progress-bar.component.html
  src/app/courses/progress-courses/courses-progress-bar.component.ts
  src/app/courses/step-view-courses/courses-step-view.component.ts
Labels: in progress

#2590 Update version
  package.json
Labels: in progress

#2556 Mutli Resource Visits Entries- 2415
  src/app/resources/view-resources/resources-viewer.component.ts
Labels: in progress

#2573 [#2569] auto focus to admin password (connects #2569)
  src/app/manager-dashboard/manager.service.ts
  src/app/shared/dialogs/dialogs-form.service.ts
Labels: in progress

#2605 [#2595] hide past attempt for parent course step view (connects #2595)
  src/app/courses/step-view-courses/courses-step-view.component.html
Labels: in progress

#2604 [#2593] push to child message (connects #2593)
  src/app/courses/courses.component.ts
  src/app/resources/resources.component.ts
Labels: in progress

#2555 Adding tooltip to show users selected (fixes #2399)
  src/app/courses/add-courses/courses-step.component.ts
  src/app/manager-dashboard/manager-dashboard.component.ts
  src/app/meetups/view-meetups/meetups-view.component.ts
  src/app/shared/dialogs/dialogs-list.component.html
  src/app/shared/dialogs/dialogs-list.component.ts
  src/app/surveys/surveys.component.ts
  src/app/teams/teams-view.component.ts
Labels: in progress

#2584 [#2549] Manager view of get courses (connects #2549)
  src/app/manager-dashboard/manager-dashboard.component.html
  src/app/manager-dashboard/manager-dashboard.component.ts
  src/app/manager-dashboard/manager.service.ts
Labels: in progress

#2578 [#2546] Show question title in exams-view component
  src/app/exams/exams-view.component.html
Labels: in progress

#2609 Update version
  package.json
Labels: in progress

#2617 Fix push to child (fixes #2614)
  src/app/manager-dashboard/manager-dashboard.component.ts
Labels: in progress
