Repository open-learning-exchange/planet, pull requests merged in 2018-12, with the labels that each got.

#2588 Disable button if already joined in a meetup (fixes #2547)
  src/app/meetups/meetups.component.html
  src/app/meetups/meetups.component.ts
Labels: in progress

#2628 [#2619] remove no attachment resource from course add resource list (connects #2619)
  src/app/courses/add-courses/courses-step.component.ts
Labels: in progress

#2638 Add new label (fixes #2501)
  .travis.yml
  couchdb-setup.sh
  src/app/resources/resources.component.html
  src/app/resources/resources.component.ts
  src/app/resources/resources.service.ts
  src/app/shared/forms/planet-tag-input-dialog.component.html
  src/app/shared/forms/planet-tag-input.component.ts
  src/app/shared/forms/tags.service.ts
Labels: priority

#2580 [#2381] Added icon to toggle password visibility
  src/app/login/login-form.component.html
  src/app/login/login-form.component.ts
  src/app/login/login.scss
Labels: in progress, reviewed

#2608 Fix exam question validation (fixes #2594)
  src/app/exams/exams-add.component.html
  src/app/exams/exams-add.component.ts
  src/app/exams/exams-question.component.html
  src/app/exams/exams-question.component.ts
  src/app/exams/exams.service.ts
  src/app/shared/forms/planet-step-list.component.ts
  src/app/validators/custom-validators.ts
Labels: in progress, priority

#2610 [2602] course name or count shown (connects #2602)
  src/app/courses/courses.service.ts
Labels: in progress

#2644 Fix console error in CoursesProgressLearner
  src/app/courses/progress-courses/courses-progress-learner.component.ts
Labels: priority

#2728 Replicate labels/tags with resources (fixes #2718)
  src/app/configuration/configuration.service.ts
  src/app/manager-dashboard/manager-dashboard.component.ts
  src/app/manager-dashboard/manager-fetch.component.ts
  src/app/resources/resources.component.ts
  src/app/shared/sync.service.ts
Labels: priority

#2730 Update Angular to 7.1
  package.json
Labels: priority

#2606 Some kind of text message of button: suggestions(fixes #2600)
  src/app/courses/view-courses/courses-view.component.html
Labels: in progress

#2515 [2425] logout-done incase of error in logout(connects #2425)
  src/app/home/home.component.ts
Labels: WIP, in progress

#2817 Fix login_activities data (fixes #2814)
  src/app/shared/couchdb.service.ts
  src/app/shared/user.service.ts
Labels: priority
