Repository open-learning-exchange/planet, pull requests merged in 2018-06, with the labels that each got.

#1152 [#937] Meaningful Level (#937)
  src/app/users/users-update/users-update.component.ts
Labels: in progress

#1206 [#1197] Created Date Sort on Request List (connects #1197)
  src/app/community/community.component.ts
Labels: in review

#1239 travis fix
  docker/planet/Dockerfile
Labels: in progress

#1240 [#1226] Do not check parent of center (connects #1226)
  src/app/manager-dashboard/manager-dashboard.component.ts
Labels: in review

#1218 [#1195] Attachment Icon in Course Steps (connects #1195)
  src/app/courses/view-courses/courses-view.component.html
  src/app/courses/view-courses/courses-view.component.ts
Labels: in progress

#1238 remove nohub from travis_utils.sh (fixes #1236)
  .travis/travis_utils.sh
Labels: in progress

#1243 [#1221] Delete user on community reject (connects #1221)
  src/app/community/community.component.ts
Labels: in review

#1251 [#1227] Use class cursor-pointer for submissions button (fixes #1227)
  src/app/dashboard/dashboard.component.html
Labels: in progress

#1252 Update version
  package.json
Labels: in progress

#1264 Vagrantfile for angular6
  Vagrantfile
Labels: in progress

#1269 [#1268] ng serve poll for changes (fixes #1268)
  angular.json
Labels: in progress

#1272 [#1258] Other user profile update top right image (connects #1258)
  src/app/users/users-update/users-update.component.ts
Labels: in progress, in review

#1266 [#1250] Mulitple Resources View in Course Step (connects #1250)
  src/app/courses/view-courses/courses-view.component.html
  src/app/courses/view-courses/courses-view.component.ts
Labels: in progress

#1276 [#1256] Delete single meetup from top bar (connects #1256)
  src/app/meetups/meetups.component.ts
Labels: in review

#1255 [#1037] Condition reversed on message (connects #1037)
  src/app/users/users.component.ts
Labels: in progress

#1279 [#1232 #1233] Fix the join/leave button not switching in meetups (fixes #1232 #1233)
  src/app/meetups/meetups.component.html
  src/app/meetups/meetups.component.ts
  src/app/meetups/view-meetups/meetups-view.component.ts
Labels: in progress

#1284 [#1271] only show unread notifications (fixes #1271)
  src/app/home/home.component.ts
Labels: in progress

#1274 Material badge notification icon (Connects #995) NEW PR
  src/app/home/home.component.html
  src/app/shared/material.module.ts
Labels: in progress

#1288 [#1234] Navigation header Meetups (connects #1234)
  src/app/meetups/view-meetups/meetups-view.component.html
Labels: in progress

#1291 [#1260] Updated Exam Page Back Button (connects #1260)
  src/app/exams/exams-add.component.html
  src/app/exams/exams-add.component.ts
Labels: in progress

#1278 [#1229] Buttons in dialog moved to the right, and correct order of them (fixes #1229)
  src/app/shared/dialogs/dialogs-form.component.html
  src/styles.scss
Labels: in progress

#1286 Correct answer for multiple choice questions (connects #668)
  src/app/courses/add-courses/courses-add.component.ts
  src/app/exams/exams-add.component.html
  src/app/exams/exams-add.component.ts
  src/app/exams/exams-add.scss
  src/app/exams/exams-question.component.html
  src/app/exams/exams-question.component.ts
  src/app/shared/utils.ts
Labels: in progress

#1294 Exams multiple choice auto correct (connects #668)
  src/app/_variables.scss
  src/app/courses/step-view-courses/courses-step-view.component.ts
  src/app/exams/exams-view.component.html
  src/app/exams/exams-view.component.ts
  src/app/submissions/submissions.service.ts
  src/styles.scss
Labels: in progress

#1254 [#1132] Replicator delete on dev mode (connects #1132)
  src/app/manager-dashboard/manager-dashboard.component.ts
Labels: in progress, in review

#1289 [#1265] Update Troubleshooting Section of README (connects #1265)
  README.md
Labels: in progress

#1273 [#1257] Add team on user list (connects #1257)
  src/app/shared/user.service.ts
  src/app/users/users.component.html
Labels: in progress, in review

#1296 Update Version
  package.json
Labels: in progress

#1324 i18n
  src/app/meetups/meetups.component.html
  src/app/resources/resources.component.html
  src/i18n/messages.xlf
Labels: in progress

#1323 update Vagrantfile (fixes #255)
  Vagrantfile
Labels: in progress

#1297 [#1295] Redirect the user to /notifications when there are no unread notifications (fixes #1295)
  src/app/home/home.component.html
Labels: in progress

#1312 [#1299] Change the default type of 'answer' in exams-view (fixes #1299)
  src/app/exams/exams-view.component.ts
Labels: in progress

#1307 Show the multiple choice answers as a list
  src/app/exams/exams-view.component.html
  src/app/exams/exams-view.component.ts
  src/app/exams/exams-view.scss
Labels: in progress

#1310 [#1308] restore the right place of the `more_vert` icon (fixes #1308)
  src/app/feedback/feedback.component.html
  src/app/resources/resources.component.html
  src/styles.scss
Labels: in progress

#1283 [#1230] Show alert when the user is not authorized to list resources/meetups/etc (fixes #1230)
  src/app/shared/couchdb.service.ts
  src/app/users/users.component.ts
Labels: in progress

#1253 [#1228] Add margin to the selects in toolbar (fixes #1228)
  src/app/meetups/meetups.component.html
  src/app/users/users.component.html
  src/styles.scss
Labels: in progress

#1314 [#1300] remove list-content-menu class which added some extra space to the submission name (fixes #1300)
  src/app/submissions/submissions.component.html
Labels: in progress

#1293 Disable submit button upon submission (fixes #1200)
  src/app/resources/resources-add.component.html
  src/app/resources/resources-add.component.ts
Labels: in progress

#1316 [#1298] Update user details view when userId is changed (fixes #1298)
  src/app/users/users-profile/users-profile.component.ts
Labels: in progress

#1322 [#1292] Remove hardcoded color in resourcesComponent (connects #1292)
  src/app/resources/resources.component.ts
Labels: in progress

#1317 [#1311] View profile data when clicking the avatar (fixes #1311)
  src/app/users/users.component.html
Labels: in progress

#1334 [#1302] UserUpdate: Do not allow birth date in the future (#1302)
  src/app/users/users-profile/users-profile.component.html
  src/app/users/users-update/users-update.component.html
  src/app/users/users-update/users-update.component.ts
Labels: in progress

#1345 Update version
  package.json
Labels: in progress

#1089 [#901] Pull selected resource from parent (connects #901)
  src/app/courses/courses.component.html
  src/app/courses/courses.component.ts
  src/app/resources/resources-add.component.ts
  src/app/resources/resources.component.html
  src/app/resources/resources.component.ts
  src/app/resources/resources.module.ts
  src/app/shared/sync.service.ts
Labels: in review, priority

#1361 New Crowdin translations
  src/i18n/messages.ara.xlf
  src/i18n/messages.eng.xlf
  src/i18n/messages.fra.xlf
  src/i18n/messages.nep.xlf
  src/i18n/messages.spa.xlf
Labels: in progress

#1281 [#1237] Update only the resource rated (fixes #1237)
  src/app/resources/rating-resources/resources-rating.component.ts
  src/app/resources/resources.service.ts
Labels: in progress

#1318 [#1305] Add placeholder to select in users (fixes #1305)
  src/app/users/users.component.html
Labels: in progress

#1315 [#1304] buttons in user component are now next to each other (fixes #1304)
  src/app/users/users.component.html
  src/app/users/users.component.ts
Labels: in progress

#1249 [#847] Separate Resource Attachments DB (connects #847)
  .travis.yml
  couchdb-setup.sh
Labels: WIP, in progress

#1365 Fixed login check center (Connects #1351)
  src/app/login/login-form.component.ts
Labels: in progress

#1371 [#1370] Undefined User Name (connects #1370)
  src/app/dashboard/dashboard.component.ts
Labels: in progress

#1373 [#1372] Meetup Form Update RevID (connects #1372)
  src/app/meetups/add-meetups/meetups-add.component.html
Labels: in progress

#1374 [#1343] Only get data for non-empty shelf (connects #1343)
  src/app/dashboard/dashboard.component.ts
Labels: in progress

#1376 Update version
  package.json
Labels: in progress

#1394 Check Latest commit (Fixes #1354)
  .travis/travis_utils.sh
Labels: in progress

#1390 [#1386] id on course (connects #1386)
  design/courses/courses-mockup.json
Labels: in progress

#1333 Manage replicator task
  src/app/app.module.ts
  src/app/courses/courses.component.ts
  src/app/home/home.module.ts
  src/app/manager-dashboard/manager-dashboard.component.ts
  src/app/manager-dashboard/manager-dashboard.module.ts
  src/app/manager-dashboard/manager-sync.component.html
  src/app/manager-dashboard/manager-sync.component.ts
  src/app/manager-dashboard/manger-dashboard-router.module.ts
  src/app/resources/resources.component.ts
  src/app/resources/resources.module.ts
  src/app/shared/sync.service.ts
Labels: in progress, in review, priority

#1337 [#1261] Remove nation component (connects #1261)
  src/app/community/community.component.html
  src/app/community/community.component.ts
  src/app/home/home-router.module.ts
  src/app/home/home.module.ts
  src/app/manager-dashboard/manager-dashboard.component.ts
  src/app/nation/nation.component.html
  src/app/nation/nation.component.spec.ts
  src/app/nation/nation.component.ts
  src/app/shared/dialogs/dialogs-list.component.html
  src/app/shared/dialogs/dialogs-list.component.ts
  src/app/shared/dialogs/dialogs-list.service.ts
Labels: in review

#1320 [#1313] Meetup can be updated only by owner (connects #1313)
  src/app/meetups/meetups.component.html
  src/app/meetups/meetups.component.ts
  src/app/meetups/view-meetups/meetups-view.component.html
  src/app/meetups/view-meetups/meetups-view.component.ts
Labels: in progress

#1411 Update version
  package.json
Labels: in progress

#1414 New Crowdin translations
  src/i18n/messages.nep.xlf
Labels: in progress

#1412 I18n
  docker/planet/Dockerfile
  docker/planet/crosscompile_planet.sh
  docker/planet/default.conf
  docker/planet/docker-entrypoint.sh
  src/i18n/messages.ara.xlf
  src/i18n/messages.eng.xlf
  src/i18n/messages.fra.xlf
  src/i18n/messages.nep.xlf
  src/i18n/messages.spa.xlf
Labels: in progress, priority

#1408 [#1396] Refactor onSubmitConfiguration (fixes #1396)
  src/app/configuration/configuration.component.ts
Labels: in progress

#1429 [#1416] profile image issue (connects #1416)
  src/app/users/users-profile/users-profile.component.html
  src/app/users/users-update/users-update.component.ts
  src/app/users/users.component.html
Labels: in progress

#1424 [#1415] Feedback Popup (connects #1415)
  src/app/home/home.module.ts
Labels: in progress

#1433 New language menu
  src/app/home/home.component.html
  src/app/home/home.component.ts
  src/app/shared/languages.ts
Labels: in progress

#1438 [#1437] Language on top bar not updating (connects #1437)
  src/app/home/home.component.ts
Labels: in progress

#1432 Fix large resource upload
  src/ngsw-config.json
Labels: in progress

#1440 Update version
  package.json
Labels: in progress

#1395 [#1348] Invalid future date error message (connects #1348)
  src/app/shared/form-error-messages.component.ts
  src/app/users/users-update/users-update.component.ts
  src/app/validators/custom-validators.ts
Labels: in progress

#1389 [#1388] Fields added to track source (connects #1388)
  design/resources/resources-mockup.json
  src/app/courses/add-courses/courses-add.component.ts
  src/app/resources/resources-add.component.html
  src/app/resources/resources-add.component.ts
  src/app/resources/resources.component.ts
Labels: in progress

#1406 [#1362] if answer.mistakes isNan, change it to 0 (fixes #1362)
  src/app/courses/progress-courses/courses-progress-leader.component.ts
Labels: in progress

#1368 [#761] Removed Item from Dashboard (connects #761)
  src/app/dashboard/dashboard-tile.component.html
  src/app/dashboard/dashboard-tile.component.ts
  src/app/dashboard/dashboard-tile.scss
  src/app/dashboard/dashboard.component.html
  src/app/dashboard/dashboard.component.ts
  src/app/shared/user.service.ts
Labels: in progress

#1402 [#1381] Add margin to mat-raised-buttons (fixes #1381)
  src/app/users/users.component.html
  src/app/users/users.component.ts
  src/styles.scss
Labels: in progress

#1410 [#877] resource-rating (connects #877)
  src/app/resources/rating-resources/resources-rating.component.ts
  src/app/shared/dialogs/dialogs-form.component.html
  src/app/shared/planet-rating.component.ts
Labels: in progress

#1443 [#1383] Add form-field inside mat-toolbat/form margin (Fixes #1383)
  src/styles.scss
Labels: in progress

#1430 [#1421] meetup check owner on delete (connects #1421)
  src/app/meetups/meetups.component.html
  src/app/meetups/meetups.component.ts
Labels: WIP

#1445 [#1431] Created the PlanetLanguage component (Fixes #1431)
  src/app/app.module.ts
  src/app/home/home.component.html
  src/app/home/home.component.ts
  src/app/home/home.module.ts
  src/app/login/login-form.component.html
  src/app/login/login.module.ts
  src/app/shared/planet-language.component.html
  src/app/shared/planet-language.component.ts
  src/app/shared/planet-language.module.ts
Labels: in progress

#1413 [#1309] background js errors (connects #1309)
  src/app/courses/step-view-courses/courses-step-view.component.html
  src/app/courses/view-courses/courses-view.component.ts
  src/app/resources/view-resources/resources-view.component.html
Labels: in progress

#1454 Fix other NaN issue
  src/app/courses/progress-courses/courses-progress-leader.component.ts
Labels: in progress

#1446 [#1423] resource_attachment (connects #1423)
  src/app/resources/resources-add.component.html
  src/app/resources/resources-add.component.ts
Labels: in progress

#1452 Update version
  package.json
Labels: in progress

#1474 New Crowdin translations
  src/i18n/messages.ara.xlf
  src/i18n/messages.eng.xlf
  src/i18n/messages.fra.xlf
  src/i18n/messages.nep.xlf
  src/i18n/messages.spa.xlf
Labels: in progress

#1407 [#1385] Use parent url in urlPrefix() variable (fixes #1385)
  src/app/resources/view-resources/resources-viewer.component.ts
Labels: in progress

#1321 Push course
  .travis.yml
  couchdb-setup.sh
  src/app/courses/courses.component.html
  src/app/courses/courses.component.ts
  src/app/manager-dashboard/manager-dashboard.component.html
  src/app/manager-dashboard/manager-dashboard.component.ts
Labels: in progress

#1499 [#1463] Exam question Input with MC choices (connects #1463)
  src/app/exams/exams-question.component.html
  src/app/exams/exams-question.component.ts
Labels: in progress

#1485 Return all documents from _find query (connects #1241)
  src/app/community/community.component.ts
  src/app/shared/couchdb.service.ts
  src/app/users/users.component.ts
Labels: in progress

#1473 [#1468] feedback view icon (connects #1468)
  src/app/feedback/feedback.component.html
Labels: in progress

#1475 [#1466] feedback suggestion icon (connects #1466)
  src/app/feedback/feedback-view.component.html
Labels: in progress

#1492 Progress bottom to top and fix total errors (connects #1201)
  src/app/courses/progress-courses/courses-progress-leader.component.html
  src/app/courses/progress-courses/courses-progress-leader.component.ts
Labels: in progress

#1486 Default user for android
  src/app/configuration/configuration.component.ts
  src/app/manager-dashboard/manager-dashboard.component.html
  src/app/manager-dashboard/manager-dashboard.component.ts
  src/app/users/users.component.ts
Labels: in progress

#1444 New approach to create docker for ARM: Don't compile in arm
  .travis/travis_utils.sh
  docker/planet/Dockerfile
  docker/planet/rpi-Dockerfile
  docker/planet/scripts/build_planet.sh
  docker/planet/scripts/compile_planet.sh
  docker/planet/scripts/crosscompile_planet.sh
  docker/planet/scripts/docker-entrypoint.sh
Labels: in progress

#1490 New Crowdin translations
  src/i18n/messages.afr.xlf
  src/i18n/messages.deu.xlf
  src/i18n/messages.hin.xlf
  src/i18n/messages.ind.xlf
  src/i18n/messages.ita.xlf
  src/i18n/messages.mlg.xlf
  src/i18n/messages.por.xlf
  src/i18n/messages.rus.xlf
  src/i18n/messages.swa.xlf
  src/i18n/messages.tam.xlf
  src/i18n/messages.tur.xlf
  src/i18n/messages.vie.xlf
  src/i18n/messages.zho.xlf
  src/i18n/messages.zul.xlf
Labels: in progress

#1495 [#1275] link updated to readme (connects #1275)
  README.md
Labels: in progress

#1347 Auto send resource course on accept
  src/app/configuration/configuration.component.ts
  src/app/manager-dashboard/manager-dashboard.component.html
  src/app/manager-dashboard/manager-dashboard.component.ts
  src/app/shared/dialogs/dialogs-list.service.ts
Labels: in progress, in review

#1479 [#1453] multi delete for admin (connects #1453)
  src/app/courses/courses.component.html
  src/app/meetups/meetups.component.html
  src/app/resources/resources.component.html
  src/app/resources/resources.component.ts
Labels: in progress

#1500 Add course progress visuals for learner (connects #1201)
  src/app/_variables.scss
  src/app/courses/courses.component.html
  src/app/courses/courses.component.ts
  src/app/courses/courses.module.ts
  src/app/courses/courses.service.ts
  src/app/courses/progress-courses/courses-progress-bar.component.html
  src/app/courses/progress-courses/courses-progress-bar.component.ts
  src/app/courses/progress-courses/courses-progress-bar.scss
  src/app/courses/step-view-courses/courses-step-view.component.ts
  src/app/courses/view-courses/courses-view.component.html
  src/app/courses/view-courses/courses-view.component.ts
  src/app/courses/view-courses/courses-view.scss
  src/styles.scss
Labels: in progress

#1482 [#1460] Default Profile Image on Remove Click (connects #1460)
  src/app/users/users-update/users-update.component.ts
Labels: in progress

#1355 Add PouchDB
  docker/planet/Dockerfile
  package.json
  src/app/app.module.ts
  src/app/shared/database/index.ts
  src/app/shared/database/pouch.service.ts
  src/polyfills.ts
  tsconfig.json
Labels: in progress

#1503 Update version
  package.json
Labels: in progress

#1498 [#1465] Sync resource along with course (connects #1465)
  src/app/courses/courses.component.ts
  src/app/courses/courses.service.ts
  src/app/manager-dashboard/manager-dashboard.component.ts
Labels: in progress
