Repository open-learning-exchange/planet, pull requests merged in 2019-09, with the labels that each got.

#4702 Migration: Fix intermittent config PUT error
  src/app/configuration/migration.component.ts
Labels: priority

#4749 UsersProfile: Fix updating password twice (fixes #4729)
  src/app/shared/user.service.ts
  src/app/users/users-profile/users-profile.component.ts
Labels: priority

#4771 Sync: Fix conflict error (fixes #4740)
  src/app/manager-dashboard/sync.directive.ts
  src/app/shared/sync.service.ts
Labels: priority

#4774 Teams: Add calendar
  angular.json
  package.json
  src/app/_variables.scss
  src/app/meetups/add-meetups/meetups-add.component.html
  src/app/meetups/add-meetups/meetups-add.component.ts
  src/app/meetups/meetups.module.ts
  src/app/meetups/view-meetups/meetups-view.component.html
  src/app/meetups/view-meetups/meetups-view.component.ts
  src/app/shared/calendar.component.ts
  src/app/shared/calendar.module.ts
  src/app/shared/dialogs/dialogs-add-meetups.component.ts
  src/app/shared/dialogs/dialogs-add-meetups.module.ts
  src/app/shared/dialogs/planet-dialogs.module.ts
  src/app/teams/teams-view.component.html
  src/app/teams/teams.module.ts
  src/styles.scss
  src/styles/calendar.scss
Labels: priority

#4762 [#4670] Course dialog component
  src/app/courses/courses.component.html
  src/app/courses/courses.component.ts
  src/app/courses/courses.module.ts
  src/app/shared/dialogs/dialogs-add-courses.component.html
  src/app/shared/dialogs/dialogs-add-courses.component.ts
  src/app/shared/dialogs/dialogs-add-courses.module.ts
  src/app/teams/teams-view.component.ts
  src/app/teams/teams.module.ts
Labels: WIP

#4841 News: Fix connected team message not showing avatar (fixes #4840)
  src/app/news/news.service.ts
Labels: priority

#4863 Show most recent visit for team members
  src/app/teams/teams-view.component.html
  src/app/teams/teams-view.component.ts
  src/app/teams/teams-view.scss
Labels: priority

#4865 TeamsView: Task tab loads after notification (fixes #4864)
  src/app/tasks/tasks.component.ts
  src/app/teams/teams-view.component.html
  src/app/teams/teams-view.component.ts
Labels: priority

#4816 4613 issue
  src/app/teams/teams-view.component.ts
Labels: priority

#4862 Calendar: Fix recurring event over multiple days (fixes #4846)
  src/app/shared/calendar.component.ts
Labels: priority

#4859 myHealth events
  src/app/health/health-event.component.html
  src/app/health/health-event.component.ts
  src/app/health/health-update.scss
  src/app/health/health.component.html
  src/app/health/health.component.ts
  src/app/health/health.module.ts
  src/app/health/health.service.ts
  src/app/home/home-router.module.ts
Labels: priority

#4903 MeetupsAdd: End time validator does not run without value (fixes #4901)
  src/app/validators/custom-validators.ts
Labels: priority

#4902 MeetupsAdd: End time requires start time (fixes #4900)
  src/app/meetups/add-meetups/meetups-add.component.ts
  src/app/validators/custom-validators.ts
Labels: priority

#4904 ExamsView: Fix grading endless spinner (fixes #4643)
  src/app/exams/exams-view.component.ts
Labels: priority

#4066 feedback title truncation (connects #3936)
  src/app/feedback/feedback-view.component.html
  src/app/feedback/feedback-view.component.ts
  src/app/feedback/feedback.directive.ts
  src/app/feedback/feedback.module.ts
  src/app/shared/utils.ts
Labels: in review
