Repository open-learning-exchange/planet, pull requests merged in 2019-05, with the labels that each got.

#3735 [Fixes #3610 ] CoursesAdd: Remove "Member Limit" and "Method"
  src/app/courses/add-courses/courses-add.component.html
  src/app/courses/add-courses/courses-add.component.ts
Labels: in progress

#3704 Questions: remove a title and display description (fixes #3701)
  package.json
  src/app/exams/exams-add.component.html
  src/app/exams/exams-add.component.ts
  src/app/exams/exams-add.scss
  src/app/exams/exams-question.component.html
  src/app/exams/exams.service.ts
Labels: in progress

#3711 Courses: add survey icon (fixes #3611)
  src/app/courses/add-courses/courses-step.component.html
  src/app/courses/view-courses/courses-view.component.html
Labels: in progress

#3730 Search course (connects #3723)
  src/app/courses/courses.component.ts
Labels: in progress

#3736 Removes Exam Title Field
  src/app/exams/exams-add.component.html
  src/app/exams/exams-add.component.ts
  src/app/exams/exams-add.scss
Labels: in progress

#3740 delete-multiple-survey(connects #3728)
  src/app/surveys/surveys.component.ts
Labels: in progress

#3731 No notification to own account (connects #3727)
  src/app/submissions/submissions.service.ts
Labels: in progress

#3739 Version 0.7.34
  package.json
Labels: in progress

#3755 Create survey (connects #3743)
  src/app/exams/exams-add.component.ts
Labels: in progress

#3756 Fix course overwrite (fixes #3600)
  src/app/courses/add-courses/courses-add.component.ts
Labels: in progress

#3758 Capitalize course in Get Course (fixes #3647)
  src/app/courses/courses.component.html
Labels: in progress

#3737 ExamQuestions: hide validation msg (fixes #3722)
  src/app/exams/exams-add.component.ts
Labels: in progress

#3716 bug fixed survey count
  src/app/surveys/surveys.component.ts
Labels: in progress

#3689 Allow renaming of community/nation on parent (fixes #3684)
  src/app/community/community-table.component.html
  src/app/community/community-table.component.ts
  src/app/community/community.component.ts
  src/app/manager-dashboard/manager.service.ts
  src/app/manager-dashboard/reports/reports-detail.component.html
  src/app/manager-dashboard/reports/reports-detail.component.ts
  src/app/manager-dashboard/reports/reports-pending.component.ts
  src/app/manager-dashboard/reports/reports-table.component.html
  src/app/manager-dashboard/reports/reports.component.ts
  src/app/manager-dashboard/reports/reports.service.ts
  src/app/shared/dialogs/dialogs-list.service.ts
  src/app/users/users.component.html
  src/app/users/users.component.ts
Labels: in progress

#3759 Time of survey notification (connects #3721)
  src/app/shared/couchdb.service.ts
Labels: in progress

#3762 Console error team view (connects #3726)
  src/app/teams/teams-view.component.ts
Labels: in progress

#3764 CoursesView: Remove Method (fixes #3748)
  src/app/courses/view-courses/courses-view.component.html
Labels: in progress

#3763 Version 0.7.35
  docker/planet/scripts/create_version_json.sh
  package.json
Labels: in progress

#3761 Exam name not saved on course (connects #3744 #3753)
  src/app/exams/exams-add.component.ts
  src/app/submissions/submissions.component.ts
Labels: in progress

#3767 [Fixes #3752] Survey: sorting missing in Course Linked column
  src/app/surveys/surveys.component.html
  src/app/surveys/surveys.component.ts
Labels: in progress

#3774 Add dash between courseName and tryNumber(fixes #3746)
  src/app/exams/exams-add.component.ts
Labels: in progress

#3697 Prevents Joining Old Meetup From Menu
  src/app/meetups/meetups.component.html
  src/app/meetups/meetups.component.ts
Labels: in progress

#3775 Update Vagrantfile
  Vagrantfile
Labels: in progress

#3705 Options for choice in survey (connects #3676)
  src/app/exams/exams-question.component.html
  src/app/exams/exams.service.ts
Labels: in progress

#3778 Fix StateService skipping changes
  src/app/shared/state.service.ts
Labels: in progress, priority

#3780 Version 0.7.36
  package.json
Labels: in progress

#3789 Achievement Resource clickable (connects #3785)
  src/app/users/users-achievements/users-achievements-update.component.html
Labels: in progress

#3729 coursedetail updated
  src/app/courses/view-courses/courses-view.component.html
Labels: in progress

#3760 List myplanet (connects #3629)
  src/app/community/community.component.ts
  src/app/manager-dashboard/manager-dashboard.component.html
  src/app/manager-dashboard/manager-dashboard.module.ts
  src/app/manager-dashboard/manager.service.ts
  src/app/manager-dashboard/manger-dashboard-router.module.ts
  src/app/manager-dashboard/reports/myplanet-table.component.html
  src/app/manager-dashboard/reports/myplanet-table.component.ts
  src/app/manager-dashboard/reports/reports-myplanet.component.html
  src/app/manager-dashboard/reports/reports-myplanet.component.ts
  src/app/manager-dashboard/reports/reports-pending.component.ts
  src/app/manager-dashboard/reports/reports.component.ts
  src/app/users/users.component.ts
Labels: in progress

#3782 Fix test question validation (fixes #3781)
  src/app/exams/exams-question.component.html
  src/app/exams/exams.service.ts
Labels: in progress, priority

#3793 Version 0.7.37
  docker/planet/scripts/create_version_json.sh
  package.json
Labels: in progress

#3773 Update collections & course collections (fixes #3772)
  src/app/courses/add-courses/courses-add.component.html
  src/app/courses/add-courses/courses-add.component.ts
  src/app/courses/courses.component.html
  src/app/courses/courses.component.ts
  src/app/courses/courses.service.ts
  src/app/courses/progress-courses/courses-progress-learner.component.ts
  src/app/courses/step-view-courses/courses-step-view.component.ts
  src/app/resources/resources-add.component.html
  src/app/resources/resources-add.component.ts
  src/app/resources/resources.component.html
  src/app/resources/resources.component.ts
  src/app/resources/resources.service.ts
  src/app/resources/view-resources/resources-view.component.html
  src/app/resources/view-resources/resources-viewer.component.ts
  src/app/shared/forms/form-error-messages.component.ts
  src/app/shared/forms/planet-tag-input-dialog.component.ts
  src/app/shared/forms/planet-tag-input.component.ts
  src/app/shared/forms/tags.service.ts
  src/app/shared/table-helpers.ts
  src/app/shared/utils.ts
  src/styles.scss
Labels: in progress, priority

#3810 Fix collections list & updates
  src/app/shared/forms/planet-tag-input-dialog.component.ts
  src/app/shared/forms/planet-tag-input.component.ts
Labels: in progress

#3809 myplanet report filter (connects #3799 #3800)
  src/app/manager-dashboard/reports/reports-myplanet.component.html
  src/app/manager-dashboard/reports/reports-myplanet.component.ts
Labels: in progress

#3807 Version 0.7.38
  package.json
Labels: in progress

#3816 Fix travis build
  package.json
  src/app/resources/resources-add.component.ts
  src/ngsw-config.json
Labels: in progress

#3779 Course Progress Bar
  src/app/courses/courses.service.ts
  src/app/submissions/submissions.service.ts
Labels: in progress

#3817 Fix resources & courses search (fixes #3815)
  src/app/courses/courses.component.html
  src/app/courses/courses.component.ts
  src/app/resources/resources.component.ts
  src/app/resources/search-resources/resources-search.component.ts
  src/app/shared/table-helpers.ts
Labels: in progress

#3814 Disable reset (connects #3802)
  src/app/courses/courses.component.html
  src/app/courses/courses.component.ts
  src/app/resources/resources.component.html
  src/app/resources/resources.component.ts
  src/app/shared/table-helpers.ts
Labels: in progress

#3791 Resource-by-title-fixed (connects #3783)
  src/app/resources/resources.component.html
Labels: in progress

#3819 Version 0.7.39
  package.json
Labels: in progress

#3837 Courses: Fix endless spinner on parent view (fixes #3824)
  src/app/courses/courses.service.ts
Labels: in progress

#3841 Fix course sync (fixes #3840)
  src/app/shared/sync.service.ts
Labels: in progress

#3838 Course: Add resource (connects #3829)
  src/app/courses/add-courses/courses-step.component.ts
Labels: in progress

#3812 Fix Course Progress's course chart label (fixes #3590)
  src/app/courses/progress-courses/courses-progress-chart.component.html
  src/app/courses/progress-courses/courses-progress-chart.component.ts
  src/app/courses/progress-courses/courses-progress-leader.component.html
  src/app/courses/progress-courses/courses-progress-leader.component.ts
Labels: in progress

#3806 The whole member rows are clickable except button(fixes #1311)
  src/app/users/users.component.html
  src/app/users/users.component.ts
Labels: in progress

#3843 [#3834] Update readme
  README.md
Labels: in progress

#3842 Replicate tags for "Get Resources" & "Get Courses"
  src/app/courses/courses.component.ts
  src/app/manager-dashboard/manager-fetch.component.ts
  src/app/manager-dashboard/manager-sync.component.ts
  src/app/shared/sync.service.ts
Labels: in progress, priority

#3818 Mimelite
  src/app/resources/resources-add.component.ts
Labels: in progress

#3835 Opens Previous Submission Whenever User Attempts to Retake Survey
  src/app/submissions/submissions.service.ts
Labels: in progress

#3839 Send Fetch course resource (connects #3813)
  src/app/manager-dashboard/manager-fetch.component.html
  src/app/shared/sync.service.ts
Labels: in progress

#3865 Courses: Fix replication without collection (fixes #3863)
  src/app/shared/sync.service.ts
Labels: priority

#3862 Manager: Fix missing fetch items components (fixes #3852)
  src/app/manager-dashboard/manager-dashboard.component.ts
  src/app/manager-dashboard/manager-fetch.component.ts
Labels: priority

#3836 Fix CoursesAdd collections error (fixes #3830)
  src/app/shared/forms/planet-tag-input.component.ts
Labels: in progress, priority

#3844 Tag validation if no change (connects #3825)
  src/app/shared/forms/planet-tag-input-dialog.component.ts
  src/app/shared/forms/tags.service.ts
Labels: in progress

#3777 Old meetup invite
  src/app/meetups/view-meetups/meetups-view.component.html
Labels: in progress

#3771 Preview of exam and survey
  src/app/courses/step-view-courses/courses-step-view.component.html
  src/app/courses/step-view-courses/courses-step-view.component.ts
  src/app/courses/view-courses/courses-view.component.html
  src/app/courses/view-courses/courses-view.component.ts
  src/app/exams/exams-add.component.html
  src/app/exams/exams-add.component.ts
  src/app/exams/exams-preview.component.ts
  src/app/exams/exams-view.component.html
  src/app/exams/exams-view.component.ts
  src/app/exams/exams.module.ts
Labels: in progress

#3776 Resources: selected collections component (fixes #3699)
  src/app/resources/resources.component.html
  src/app/resources/resources.scss
  src/app/shared/forms/planet-forms.module.ts
  src/app/shared/forms/planet-tag-input.component.html
  src/app/shared/forms/planet-tag-input.component.ts
  src/app/shared/forms/planet-tag-selected-input.component.ts
  src/app/shared/planet-filtered-amount.component.ts
Labels: in progress

#3894 Upgrade: Fix credentials.yml not generating (fixes #3893)
  src/app/manager-dashboard/manager.service.ts
Labels: priority

#3792 [#3766] Show community name on survey list
  src/app/shared/dialogs/dialogs-list.component.ts
  src/app/surveys/surveys.component.ts
Labels: in progress

#3895 Fix admin change password (fixes #3072)
  src/app/shared/dialogs/change-password.directive.ts
Labels: priority

#3927 ExamsAdd redesign
  src/app/courses/add-courses/courses-step.component.ts
  src/app/exams/exams-add.component.html
  src/app/exams/exams-add.component.ts
  src/app/exams/exams-add.scss
  src/app/exams/exams-question.component.html
  src/app/exams/exams-question.scss
  src/app/shared/forms/planet-markdown-textbox.scss
  src/app/shared/forms/planet-step-list.component.ts
  src/app/shared/forms/planet-step-list.scss
Labels: priority

#3928 Teams: Add feed of messages
  src/app/home/home.module.ts
  src/app/news/news-list.component.html
  src/app/news/news-list.component.ts
  src/app/news/news.component.html
  src/app/news/news.component.ts
  src/app/news/news.module.ts
  src/app/news/news.scss
  src/app/news/news.service.ts
  src/app/teams/teams-view.component.html
  src/app/teams/teams-view.component.ts
  src/app/teams/teams-view.scss
  src/app/teams/teams.module.ts
Labels: priority
