Repository open-learning-exchange/planet, pull requests merged in 2019-08, with the labels that each got.

#4463 Resources & Courses: Increase font size of collections button
  src/app/courses/courses.component.html
  src/app/resources/resources.component.html
  src/app/shared/forms/planet-tag-input.component.html
  src/app/shared/forms/planet-tag-input.component.ts
Labels: priority

#4459 Vagrant: Fix member creation error in development (fixes #2470)
  README.md
  Vagrantfile
  couchdb-setup.sh
  v-couchdb-setup.sh
Labels: priority

#4221 Upgrade to Angular 8
  .travis.yml
  browserslist
  docker/db-init/Dockerfile
  docker/planet/Dockerfile
  e2e/login.e2e-spec.ts
  e2e/userHandler.ts
  package.json
  protractor.conf.js
  src/app/app-router.module.ts
  src/app/community/community-table.component.ts
  src/app/configuration/configuration.component.ts
  src/app/courses/courses.component.ts
  src/app/courses/progress-courses/courses-progress-chart.component.ts
  src/app/dashboard/dashboard-tile.component.ts
  src/app/feedback/feedback-view.component.ts
  src/app/feedback/feedback.component.ts
  src/app/home/home-router.module.ts
  src/app/home/home.component.ts
  src/app/manager-dashboard/manager-fetch.component.ts
  src/app/manager-dashboard/manger-dashboard-router.module.ts
  src/app/manager-dashboard/reports/myplanet-table.component.ts
  src/app/manager-dashboard/reports/pending-table.component.ts
  src/app/manager-dashboard/reports/reports-table.component.ts
  src/app/meetups/meetups.component.ts
  src/app/news/news-list-item.component.ts
  src/app/notifications/notifications.component.ts
  src/app/resources/resources.component.ts
  src/app/resources/search-resources/resources-search.component.ts
  src/app/resources/view-resources/resources-menu.component.ts
  src/app/shared/dialogs/dialogs-add-resources.component.ts
  src/app/shared/dialogs/dialogs-list.component.ts
  src/app/shared/forms/planet-step-list.component.ts
  src/app/shared/user.service.ts
  src/app/submissions/submissions.component.ts
  src/app/surveys/surveys.component.ts
  src/app/teams/teams-router.module.ts
  src/app/teams/teams.component.ts
  src/app/users/users.component.ts
  src/polyfills.ts
  src/tsconfig.app.json
  src/tsconfig.spec.json
  tsconfig.json
  tslint.json
Labels: priority

#2240 Update PouchDB Service and auth
  src/app/login/login-form.component.ts
  src/app/shared/database/pouch-auth.service.ts
  src/app/shared/database/pouch.service.ts
Labels: in progress

#3364 [#3346] no post data on update of course and resource (connects #3346)
  src/app/resources/resources-add.component.ts
  src/app/shared/dialogs/dialogs-add-resources.component.ts
Labels: WIP, in progress

#4522 Upgrade: Don't show success message after error (fixes #2983)
  src/app/upgrade/upgrade.component.ts
Labels: priority

#4483 Setup: Remove activity_logs from script
  couchdb-setup.sh
  design/security-update/security-update.json
Labels: priority

#4520 Dashboard: Fix visits limited to 1000 (fixes #4512)
  src/app/dashboard/dashboard.component.ts
Labels: priority

#4566 Collections: Fix adding a subcollection
  src/app/shared/forms/planet-tag-input-dialog.component.html
  src/app/shared/forms/planet-tag-input-dialog.component.ts
Labels: priority

#4567 Collections: Add new subcollection selects main
  src/app/shared/forms/planet-tag-input-dialog.component.ts
Labels: priority

#4580 Teams: Stop team routing for button clicks (fixes #4579)
  src/app/teams/teams.component.html
Labels: priority

#4484 Courses: Select only one collection at a time
  src/app/courses/courses.component.html
  src/app/shared/forms/planet-tag-input-dialog.component.ts
  src/app/shared/forms/planet-tag-input.component.ts
Labels: priority

#4525 TeamsView: Add tasks for team
  .travis.yml
  couchdb-setup.sh
  src/app/shared/shared-components.module.ts
  src/app/tasks/tasks.component.html
  src/app/tasks/tasks.component.ts
  src/app/tasks/tasks.scss
  src/app/tasks/tasks.service.ts
  src/app/teams/teams-view.component.html
  src/app/teams/teams-view.component.ts
  src/app/teams/teams-view.scss
Labels: priority

#4578 User image replication
  src/app/manager-dashboard/sync.directive.ts
  src/app/shared/user.service.ts
  src/app/teams/teams-view.component.html
  src/app/teams/teams-view.component.ts
  src/app/teams/teams.component.ts
  src/app/teams/teams.service.ts
Labels: priority

#4620 [#4599] Team task sync
  src/app/manager-dashboard/sync.directive.ts
  src/app/tasks/tasks.component.ts
  src/app/teams/teams-view.component.html
Labels: WIP

#4576 TeamsView: Refactor DialogsPromptComponent (fixes #4396)
  src/app/teams/teams-view.component.html
  src/app/teams/teams-view.component.ts
Labels: priority

#4625 Ratings: Decrease time to fetch course ratings
  src/app/courses/courses.service.ts
  src/app/shared/forms/rating.service.ts
  src/app/shared/mangoQueries.ts
Labels: priority

#4618 Teams: Fix no response after joining connected team (fixes #4587)
  src/app/shared/user.service.ts
Labels: priority

#4629 Courses & Resources: Improve speed
  src/app/courses/courses.component.html
  src/app/courses/courses.component.ts
  src/app/resources/resources.component.html
  src/app/resources/resources.component.ts
  src/app/shared/table-helpers.ts
Labels: priority

#4633 Tasks: Fix assigning member from other planet (fixes #4630)
  src/app/tasks/tasks.component.html
  src/app/tasks/tasks.component.ts
Labels: priority

#4673 Courses: Change progress label (fixes #4223)
  src/app/courses/view-courses/courses-view.component.html
Labels: priority

#4684 Enterprises beta
  src/app/home/home-router.module.ts
  src/app/home/home.component.html
  src/app/home/home.component.ts
  src/app/teams/teams-view-finances.component.html
  src/app/teams/teams-view-finances.component.ts
  src/app/teams/teams-view.component.html
  src/app/teams/teams-view.component.ts
  src/app/teams/teams.component.html
  src/app/teams/teams.component.ts
  src/app/teams/teams.module.ts
  src/app/teams/teams.service.ts
Labels: priority
