Repository open-learning-exchange/planet, pull requests merged in 2019-03, with the labels that each got.

#3153 Connect team to course on TeamsView
  src/app/teams/teams-view.component.html
  src/app/teams/teams-view.component.ts
Labels: in progress

#3315 Achievements pdf dogi
  docker/planet/Dockerfile
Labels: in progress

#3308 Dialog: add rating confirm button (fixes #3300)
  src/app/shared/dialogs/dialogs-form.component.html
  src/app/shared/forms/planet-rating.component.ts
Labels: in progress

#3290 [#3281] Sort achievement view (connects #3281)
  src/app/users/users-achievements/users-achievements-update.component.html
  src/app/users/users-achievements/users-achievements-update.component.ts
Labels: in progress

#3204 (Fixes #2743) Submissions: Clarify Grading Status
  src/app/submissions/submissions.component.html
  src/app/submissions/submissions.service.ts
Labels: in progress

#3311 [#3295] hide submittedBy on mySurvey (connects #3295)
  src/app/submissions/submissions.component.ts
Labels: in progress

#3310 [Fixes #1301] Grading Status of Auto Correct
  src/app/submissions/submissions.service.ts
Labels: in progress

#3317 Update version
  docker/planet/scripts/create_version_json.sh
  package.json
Labels: in progress

#3330 [Fixes #3327] Hide Empty Fields in Meetups
  src/app/meetups/view-meetups/meetups-view.component.html
Labels: in progress

#3333 Adding toolbar for "upgrade" component(fixes #3248)
  src/app/upgrade/upgrade.component.html
Labels: in progress

#3316 New monitor role & directive for hiding content based on roles
  src/app/dashboard/dashboard.component.html
  src/app/home/home.component.html
  src/app/manager-dashboard/manager-dashboard.component.html
  src/app/manager-dashboard/manager-dashboard.component.ts
  src/app/manager-dashboard/manager-dashboard.module.ts
  src/app/shared/authorized-roles.directive.ts
  src/app/shared/shared-components.module.ts
  src/app/shared/user.service.ts
  src/app/users/users.component.ts
Labels: in progress

#3312 [Fixes #2904] hover on pending submission
  src/app/submissions/submissions.component.html
  src/app/submissions/submissions.component.ts
Labels: in progress

#3335 [Fixes #3301] Survey: no. of time taken should not count status "pending"
  src/app/surveys/surveys.component.ts
Labels: in progress

#3329 [#3320] mySurvey count fixes (connects #3320)
  src/app/dashboard/dashboard.component.html
  src/app/dashboard/dashboard.component.ts
Labels: in progress

#3313 [Fixes #3275] Survey: spacing between action buttons when disabled
  src/styles.scss
Labels: in progress

#3338 Version 0.7.15
  package.json
Labels: in progress

#3340 Proxy update (connects #3336)
  docker/planet.yml
  docker/planet/default.conf
Labels: in progress

#3358 Update version
  package.json
Labels: in progress

#3361 [Fixes #3348] Notification: meetup fixes
  src/app/meetups/view-meetups/meetups-view.component.ts
Labels: in progress

#3362 [#3347] submission cursor pointer on Pending (connects #3347)
  src/app/submissions/submissions.component.html
Labels: in progress

#3356 [#3322] team requested member list (connects #3322)
  src/app/teams/teams-view.component.html
Labels: in progress

#3366 [#3274]email-validation-added-in-achievement-reference(connects #3274)
  src/app/users/users-achievements/users-achievements-update.component.ts
Labels: in progress

#3353 [Fixes #3339] Edit Achievement: Uppercase fixes of reference and date
  src/app/users/users-achievements/users-achievements-update.component.html
Labels: in progress

#3367 [Fixes #3299] Separator on Course Steps
  src/app/courses/view-courses/courses-view.component.html
Labels: in progress

#3369 File Server (connects #3211)
  docker/planet/scripts/docker-entrypoint.sh
  docker/volumes.yml
Labels: in progress

#3368 [Fixes #3297] Link to User Profile of Team Members
  src/app/teams/teams-view.component.html
Labels: in progress

#3355 [#3325] Filter submission by status (connects #3325)
  src/app/submissions/submissions.component.html
  src/app/submissions/submissions.component.ts
Labels: in progress

#3351 Fix missing parent buttons (fixes #3341)
  src/app/manager-dashboard/manager-dashboard.component.html
Labels: in progress

#3318 Title overflow (fixes #2213, connects PR #1856 and #2144)
  src/app/courses/step-view-courses/courses-step-view.component.html
  src/app/courses/view-courses/courses-view.component.html
  src/app/meetups/view-meetups/meetups-view.component.html
  src/app/resources/view-resources/resources-view.component.html
  src/app/teams/teams-view.component.html
  src/styles.scss
Labels: in progress

#3370 Update version
  docker/planet/scripts/create_version_json.sh
  package.json
Labels: in progress

#3372 Fix monitor reports error (fixes #3343)
  design/security-update/security-update.json
Labels: in progress

#3384 [#3381] User role on dashboard
  src/app/dashboard/dashboard.component.html
  src/app/dashboard/dashboard.component.ts
Labels: in progress

#3393 [Fixes #3374] mySurvey: Survey title change to mySurvey
  src/app/dashboard/dashboard.component.html
  src/app/submissions/submissions.component.html
Labels: in progress

#3394 Notification See all pin to bottom (connects #2906)
  src/app/home/home.component.html
  src/styles.scss
Labels: in progress

#3396 Add ourNews
  .travis.yml
  couchdb-setup.sh
  src/app/dashboard/dashboard.component.html
  src/app/home/home-router.module.ts
  src/app/home/home.component.ts
  src/app/home/home.module.ts
  src/app/news/news.component.html
  src/app/news/news.component.ts
  src/app/news/news.scss
Labels: priority

#3383 [Fixes #3379] Remove 'Not Graded' From Survey Status Options
  src/app/submissions/submissions.component.html
Labels: in progress

#3363 [Fixes #3245] Achievement button on my profile view
  src/app/users/users-profile/users-profile.component.html
Labels: in progress

#3390 Fixing NameCell and Cursor in Submissions(Fixes #3371)
  src/app/submissions/submissions.component.html
Labels: in progress

#3389 Fixing date.ValueToJson() bug in achievement-update (Fixes #3342)
  src/app/users/users-achievements/users-achievements-update.component.ts
Labels: in progress

#3397 Update version
  package.json
Labels: in progress

#3387 Update center url (connects #3380)
  docker/planet.yml
  src/environments/environment.test.ts
  src/environments/environment.ts
Labels: in progress

#3423 [Fixes #3349] Surveys: Column widths
  src/app/surveys/surveys.component.ts
Labels: in progress

#3418 user-link-added (fixes #3402)
  src/app/news/news.component.html
Labels: in progress

#3417 [#3406] image-alligned-with-name(connects #3406)
  src/app/news/news.component.html
Labels: in progress

#3416 News edit and delete (connects #3399)
  src/app/news/news.component.html
  src/app/news/news.component.ts
Labels: in progress

#3425 News: Fix indentation and spacing
  src/app/news/news.component.html
Labels: in progress

#3426 News: Action button changes
  src/app/news/news.component.html
  src/app/news/news.component.ts
Labels: in progress

#3411 [Fixes #3377] View User Profiles of Team Join Requests
  src/app/teams/teams-view.component.html
Labels: in progress

#3414 [Fixes #3098] Drag and Drop Dashboard Items
  src/app/dashboard/dashboard-tile.component.html
  src/app/dashboard/dashboard-tile.component.ts
  src/app/shared/material.module.ts
Labels: in progress

#3420 Checkbox removed in users in non-admin( fixes #3404)
  src/app/users/users.component.ts
Labels: in progress

#3388 [#3186] resources-sorting(connects #3186)
  couchdb-setup.sh
  src/app/resources/resources.service.ts
  src/app/shared/state.service.ts
Labels: in progress

#3421 [#3395] updateuser without credential info (connects #3395)
  src/app/shared/user.service.ts
Labels: in progress

#3428 Version 0.7.19
  docker/planet/scripts/create_version_json.sh
  package.json
Labels: in progress

#3422 markdown post (fixes #3412)
  src/app/news/news.component.html
  src/app/news/news.component.ts
  src/app/shared/dialogs/dialogs-form.component.html
  src/app/shared/forms/planet-markdown-textbox.component.ts
Labels: in progress

#3442 [#3434] File upload config
  src/app/users/users-update/users-update.component.html
  src/app/users/users-update/users-update.component.ts
Labels: in progress

#3435 [#3403] Reset Dropdown When Switching Between Exams & Surveys
  src/app/submissions/submissions.component.ts
Labels: in progress

#3443 sort added in basedbs fixes #3437
  src/app/shared/state.service.ts
Labels: in progress

#3451 Removed fields in add resources (connects #3438)
  src/app/resources/resources-add.component.html
  src/app/resources/resources-add.component.ts
Labels: in progress

#3449 Fix admin update error (fixes #3350)
  src/app/shared/user.service.ts
Labels: in progress, priority

#3448 Additional resource filters
  src/app/resources/resources.component.html
  src/app/resources/resources.component.ts
  src/app/resources/resources.module.ts
  src/app/resources/resources.scss
  src/app/resources/search-resources/resources-search.component.ts
  src/app/resources/search-resources/resources-search.scss
  src/app/shared/table-helpers.ts
Labels: in progress, priority

#3452 Update version to 0.7.20
  package.json
Labels: in progress

#3464 [Fixes #3457] Member Search : Change search filter placeholder
  src/app/users/users.component.html
Labels: in progress

#3465 [Fixes #3431] UI improvement
  src/app/teams/teams-view.component.html
  src/app/teams/teams.component.html
Labels: in progress

#3430 Course & resource: add edit button (fixes #2719)
  src/app/courses/view-courses/courses-view.component.html
  src/app/courses/view-courses/courses-view.component.ts
  src/app/resources/view-resources/resources-view.component.html
  src/app/resources/view-resources/resources-view.component.ts
Labels: in progress

#3446 [Fixes #3432] Add Edit Date to News Post
  src/app/news/news.component.html
  src/app/news/news.component.ts
Labels: in progress

#3391 Resources: add many collections (fixes #3385)
  src/app/resources/resources.component.html
  src/app/resources/resources.component.ts
  src/app/resources/resources.service.ts
  src/app/shared/forms/planet-tag-input-dialog.component.html
  src/app/shared/forms/planet-tag-input-dialog.component.ts
  src/app/shared/forms/planet-tag-input.component.html
  src/app/shared/forms/planet-tag-input.component.ts
  src/app/shared/forms/rating.service.ts
Labels: in progress, priority

#3463 [#3450] myLibrary Filter
  src/app/dashboard/dashboard-tile.component.html
  src/app/dashboard/dashboard-tile.component.ts
  src/app/dashboard/dashboard.component.html
  src/app/home/home-router.module.ts
  src/app/resources/resources.component.html
  src/app/resources/resources.component.ts
Labels: in progress

#3453 [Fixes #3433] ourNews: Edit title should be changed to "New Post"
  src/app/news/news.component.ts
Labels: in progress

#3154 Show/hide beta features
  src/app/configuration/configuration.component.html
  src/app/configuration/configuration.component.ts
  src/app/shared/beta.directive.ts
  src/app/shared/shared-components.module.ts
  src/app/users/users-update/users-update.component.html
  src/app/users/users-update/users-update.component.ts
Labels: in progress, priority

#3470 [#3440] update README.md (fixes #3440)
  README.md
Labels: in progress

#3447 Surveys: delete surveys (fixes #2751)
  src/app/shared/couchdb.service.ts
  src/app/shared/utils.ts
  src/app/surveys/surveys.component.html
  src/app/surveys/surveys.component.ts
  src/app/surveys/surveys.module.ts
Labels: in progress

#3468 Version 0.7.21
  docker/planet/scripts/create_version_json.sh
  package.json
Labels: in progress

#3467 [#3419] selection-cleared-from filter
  src/app/resources/resources.component.ts
  src/app/shared/table-helpers.ts
Labels: in progress

#3481 [#3475] Reset selection on mylibrary toggle
  src/app/resources/resources.component.ts
Labels: in progress, priority

#3484 Version 0.7.22
  package.json
Labels: in progress

#3472 [Fixes #3324] Notification link should be disable for user with no role
  src/app/home/home.component.html
Labels: in progress

#3485 [#3474] beta-toggle-hidden(connects #3474)
  src/app/users/users-update/users-update.component.html
Labels: in progress

#3487 GET /update/planetapk
  docker/planet/Dockerfile
  docker/planet/default.conf
  docker/planet/nginx/upgrade_planetapk.sh
  docker/planet/nginx/upgrade_planetapk_fromnation.sh
Labels: difficult, enhancement, in progress, priority

#3489 Version 0.7.23
  package.json
Labels: in progress
