Repository open-learning-exchange/planet, pull requests merged in 2019-02, with the labels that each got.

#3121 [#3111] achievement update fixes (connects #3111)
  src/app/users/users-achievements/users-achievements-update.component.html
Labels: priority

#3132 View other member achievements as admin (fixes #3129)
  src/app/home/home.module.ts
  src/app/users/users-achievements/users-achievements.component.html
  src/app/users/users-achievements/users-achievements.component.ts
  src/app/users/users-achievements/users-achievements.module.ts
  src/app/users/users-profile/users-profile.component.html
  src/app/users/users-router.module.ts
  src/app/users/users.module.ts
Labels: priority

#3131 Achievements replicate on sync (fixes #3128)
  src/app/manager-dashboard/manager-sync.component.ts
  src/app/shared/sync.service.ts
  src/app/users/users-achievements/users-achievements-update.component.ts
  src/app/users/users-achievements/users-achievements.component.ts
  src/app/users/users-achievements/users-achievements.service.ts
Labels: priority

#3074 Add resources to achievements (fixes #3041)
  src/app/courses/add-courses/courses-step.component.ts
  src/app/courses/view-courses/courses-view.component.html
  src/app/courses/view-courses/courses-view.component.ts
  src/app/resources/view-resources/resources-menu.component.ts
  src/app/shared/dialogs/dialogs-form.component.html
  src/app/shared/dialogs/dialogs-form.component.ts
  src/app/shared/dialogs/dialogs-list.service.ts
  src/app/shared/shared-components.module.ts
  src/app/users/users-achievements/users-achievements-update.component.html
  src/app/users/users-achievements/users-achievements-update.component.ts
  src/app/users/users-achievements/users-achievements.component.html
  src/app/users/users-achievements/users-achievements.scss
Labels: priority

#3148 Fix font for production & error messages
  src/styles/_mixins.scss
  src/styles/_variables.scss
Labels: in progress

#3146 [3143]-hide-achievement(connects #3143)
  src/app/users/users-profile/users-profile.component.html
  src/app/users/users-profile/users-profile.component.ts
Labels: in progress

#3149 AchievementsUpdate edits (fixes #3147)
  src/app/users/users-achievements/users-achievements-update.component.html
  src/app/users/users-achievements/users-achievements.service.ts
Labels: in progress

#3155 [#3142] view child achievement (connects #3142)
  src/app/users/users-achievements/users-achievements.component.ts
Labels: in progress

#3156 [#3139] add other info spinner stuck fixes (connects #3139)
  src/app/shared/dialogs/dialogs-loading.service.ts
  src/app/users/users-achievements/users-achievements-update.component.ts
Labels: in progress

#3159 Improve Button for Achievements (Fixes #3141)
  src/app/users/users-profile/users-profile.component.html
Labels: in progress

#3151 Update README.md
  README.md
Labels: in progress

#3160 Achievements: fix textbox in fullscreen mode (fixes #3089)
  src/app/shared/forms/planet-markdown-textbox.scss
Labels: in progress

#3157 [#3136] UpgradeComponent month fixes (connects #3136)
  src/app/upgrade/upgrade.component.ts
Labels: in progress

#3161 Achievements: change text alignment (fixes #3062)
  src/app/users/users-achievements/users-achievements.component.html
  src/app/users/users-achievements/users-achievements.component.ts
  src/app/users/users-achievements/users-achievements.scss
Labels: in progress

#3158 [#3135] achievement UI fixes (connects #3135)
  src/app/users/users-achievements/users-achievements-update.scss
  src/app/users/users-achievements/users-achievements.scss
Labels: in progress

#3162 Session: increase session timeout (fixes #3119)
  couchdb-setup.sh
Labels: in progress

#3164 Update version
  docker/planet/scripts/create_version_json.sh
  package.json
Labels: in progress

#3182 [#3163] Sync myplanet db (connects #3163)
  src/app/manager-dashboard/manager-sync.component.ts
Labels: in progress

#3181 [#3167] Relative back from achievement (connects #3167)
  src/app/users/users-achievements/users-achievements.component.ts
Labels: in progress

#3180 Fix missing doc causing no items in dashboard (fixes #3096)
  src/app/shared/couchdb.service.ts
Labels: in progress, priority

#3183 ExamsView: Require text for answers (fixes #2845)
  src/app/exams/exams-view.component.html
  src/app/exams/exams-view.component.ts
Labels: in progress, priority

#3179 Users: Only show accepted communities in children list (fixes #3168)
  src/app/users/users.component.ts
Labels: in progress, priority

#3173 [3138]-achievement-validator-progress(connects #3138)
  src/app/users/users-achievements/users-achievements-update.component.ts
Labels: in progress

#3184 Update version
  package.json
Labels: in progress

#3165 (Fixes #2961) Make Readonly Text Grey
  src/app/resources/resources-add.component.html
  src/styles.scss
Labels: in progress

#3196 [#2846] Leave team archive issue fixed (connects #2846)
  src/app/dashboard/dashboard-tile.component.ts
  src/app/teams/teams-view.component.ts
Labels: in progress

#3177 (Fixes #3137) Changes Button to Edit Achievement Button
  src/app/users/users-achievements/users-achievements.component.html
Labels: in progress

#3197 [#3189] member with learner role resstricted to manage (connects #3189)
  src/app/resources/resources.component.html
  src/app/resources/resources.component.ts
Labels: in progress

#3200 Dashboard: split long title (fixes #3187)
  src/app/dashboard/dashboard-tile.scss
Labels: in progress

#3201 [3191]-edit-achievement-fixed (connects #3191) (connects #3193)
  src/app/users/users-achievements/users-achievements.component.html
Labels: in progress

#3203 [#3166] add personal information dialog box title fixes (connects #3166)
  src/app/users/users-achievements/users-achievements-update.component.ts
Labels: in progress

#3199 Achievements: update with no achievements (fixes #3188)
  src/app/users/users-achievements/users-achievements.component.ts
  src/app/users/users-achievements/users-achievements.service.ts
  src/app/users/users-profile/users-profile.component.ts
Labels: in progress

#3206 Fixes #3130
  src/app/manager-dashboard/manager-fetch.component.ts
  src/app/manager-dashboard/manager-sync.component.ts
  src/app/resources/resources.component.ts
  src/app/shared/sync.service.ts
Labels: in progress

#3213 Surveys: sort by date (fixes #2913)
  src/app/surveys/surveys.component.html
  src/app/surveys/surveys.component.ts
Labels: in progress

#3210 [#3209] ole/stretch64 0.7.9 (fixes #3209)
  Vagrantfile
Labels: in progress

#3212 Update version
  docker/planet/scripts/create_version_json.sh
  package.json
Labels: in progress

#3226 Achievements: remove personal Info (fixes #3222)
  src/app/users/users-achievements/users-achievements-update.component.html
  src/app/users/users-achievements/users-achievements-update.component.ts
  src/app/users/users-achievements/users-achievements.component.html
  src/app/users/users-achievements/users-achievements.component.ts
  src/app/users/users-achievements/users-achievements.service.ts
Labels: in progress

#3227 [#3224] edit-achievement-button (connects #3224)
  src/app/users/users-achievements/users-achievements.component.html
Labels: in progress

#3228 [#3223] title-date-added-in-achievement(connects #3223)
  src/app/shared/dialogs/dialogs-form.component.html
  src/app/users/users-achievements/users-achievements-update.component.html
  src/app/users/users-achievements/users-achievements-update.component.ts
Labels: in progress

#3229 (Fixes #2781) Show In Progress/Loading When Ryn Sync Is Clicked
  src/app/manager-dashboard/manager-sync.component.ts
Labels: in progress

#3231 Dialogs: disable submit button (fixes #2908)
  src/app/shared/dialogs/dialogs-form.component.html
  src/app/shared/dialogs/dialogs-form.component.ts
Labels: in progress

#3230 Fix first sync error (fixes #3114)
  src/app/manager-dashboard/manager-sync.component.ts
Labels: in progress, priority

#3233 Achievements: Rearrange to include title & date (fixes #3232)
  src/app/resources/view-resources/resources-menu.component.ts
  src/app/users/users-achievements/users-achievements.component.html
  src/app/users/users-achievements/users-achievements.component.ts
  src/app/users/users-achievements/users-achievements.scss
Labels: in progress, priority

#3234 Achievements: Add profile fields (fixes #3198)
  src/app/shared/user.service.ts
  src/app/users/users-achievements/users-achievements-update.component.html
  src/app/users/users-achievements/users-achievements-update.component.ts
  src/app/users/users-achievements/users-achievements-update.scss
  src/app/users/users-achievements/users-achievements.component.html
  src/app/users/users-update/users-update.component.html
  src/app/users/users-update/users-update.component.ts
Labels: in progress, priority

#3236 Achievements: Add references (fixes #3235)
  src/app/users/users-achievements/users-achievements-update.component.html
  src/app/users/users-achievements/users-achievements-update.component.ts
  src/app/users/users-achievements/users-achievements.component.html
Labels: in progress, priority

#3237 Update version
  package.json
Labels: in progress

#3255 Achievements: Fix removing user's credentials (fixes #3250)
  src/app/users/users-achievements/users-achievements-update.component.ts
Labels: in progress

#3263 Fixes #3219
  src/app/users/users-achievements/users-achievements-update.component.ts
Labels: in progress

#3258 Fixes #3215
  src/app/home/home.component.ts
Labels: in progress

#3266 [Fixes #3220] Achievement: Change the Label in the Dialog Box
  src/app/users/users-achievements/users-achievements-update.component.ts
Labels: in progress

#3262 [#3249] achievement-reference-fixes(connects #3249)
  src/app/users/users-achievements/users-achievements.service.ts
Labels: in progress

#3264 [#3247] Survey user reduce expect unknown (connects #3247)
  src/app/submissions/submissions.component.ts
Labels: in progress

#3268 [Fixes #3240] Achievement: Middle name missing in name
  src/app/users/users-achievements/users-achievements.component.html
Labels: in progress

#3253 [#3242]-profile-validation-added (connects #3242)
  src/app/users/users-achievements/users-achievements-update.component.html
  src/app/users/users-achievements/users-achievements-update.component.ts
Labels: in progress

#3254 (Fixes #3239) Achievements: My References
  src/app/users/users-achievements/users-achievements.component.html
Labels: in progress

#3257 Dialog: enable submit button for resources (fixes #3241)
  src/app/shared/dialogs/dialogs-form.component.ts
Labels: in progress

#3259 Sort resources by title (connects #3244)
  src/app/users/users-achievements/users-achievements-update.component.ts
Labels: in progress

#3256 Achievements: add icons and isClickable check (fixes #3251)
  src/app/users/users-achievements/users-achievements.component.html
  src/app/users/users-achievements/users-achievements.component.ts
  src/app/users/users-achievements/users-achievements.scss
Labels: in progress

#3202 (Fixes #3194) See Profile of User Submitting Exam or Survey
  src/app/submissions/submissions.component.html
  src/app/submissions/submissions.component.ts
Labels: in progress

#3282 [Fixes #3272] Resolves Remainder of #3238
  src/app/users/users-achievements/users-achievements-update.component.ts
Labels: in progress

#3284 [#3280]-collection-list-shown (connects #3280)
  src/app/resources/resources.service.ts
  src/app/resources/view-resources/resources-view.component.html
Labels: in progress

#3288 [#3285] Lowercase username (connects #3285)
  src/app/configuration/configuration.module.ts
  src/app/login/login.module.ts
  src/app/shared/shared-components.module.ts
Labels: in progress

#3286 [#3283] multiple-choice-label-added(connects #3283)
  src/app/exams/exams-view.component.html
Labels: in progress

#3289 [#3277] add-question-removed(connects #3277)
  src/app/exams/exams-add.component.html
Labels: in progress

#3291 [Fixes #3273] Hides Title of Unavailable Data
  src/app/users/users-achievements/users-achievements.component.html
Labels: in progress

#3292 Resources: Remove redundant tags request
  src/app/resources/resources.component.ts
Labels: in progress

#3287 [#3279] message-added-for-no-steps(connects #3279)
  src/app/courses/view-courses/courses-view.component.html
Labels: in progress

#3207 [#3190] hide unaccepeted community registration request from send sur… (connects #3190)
  src/app/surveys/surveys.component.ts
Labels: in progress

#3294 Version 0.7.13
  package.json
Labels: in progress
