Repository open-learning-exchange/planet, pull requests merged in 2023-10, with the labels that each got.

#7269 home: add myChat link in myLibrary box (fixes #7268)
  package.json
  src/app/dashboard/dashboard-tile.component.html
Labels: ready to merge

#7277 actions: bump `actions/checkout` to 4 (fixes #7275)
  .github/workflows/deploy.yml
  .github/workflows/planet-chat.yml
  .github/workflows/planet-db.yml
  .github/workflows/planet.yml
  package.json
Labels: hacktoberfest-accepted

#7276 courses: camelcasing myProgress (fixes #7274)
  package.json
  src/app/courses/add-courses/courses-add.scss
  src/app/courses/courses.component.html
  src/app/courses/progress-courses/courses-progress-learner.component.html
  src/app/courses/view-courses/courses-view.component.html
  src/app/resources/resources-add.scss
Labels: ready to merge

#7273 courses: markdown block images (fixes #7272)
  package.json
  src/app/courses/step-view-courses/courses-step-view.component.html
  src/app/courses/view-courses/courses-view-detail.component.html
  src/app/courses/view-courses/courses-view.component.html
  src/app/shared/planet-markdown.scss
Labels: ready to merge

#7280 courses: better table sizes (fixes #7279)
  package.json
  src/app/courses/courses.component.html
  src/app/courses/courses.scss
  src/app/resources/resources.component.html
  src/app/resources/resources.scss
  src/styles.scss
Labels: ready to merge

#7282 courses: new height handling in view dialog (fixes #7278)
  package.json
  src/app/dashboard/dashboard.component.html
  src/app/dashboard/dashboard.component.ts
  src/app/manager-dashboard/reports/reports-detail.component.ts
  src/app/teams/teams-view.component.ts
Labels: ready to merge

#7281 courses: better handling long titles (fixes #7259)
  package.json
  src/app/courses/courses.component.html
  src/app/resources/resources.component.html
  src/styles.scss
Labels: ready to merge

#7283 courses: improve filter stability (fixes #7261)
  package.json
  src/app/courses/courses.component.ts
  src/app/shared/table-helpers.ts
Labels: ready to merge

#7208 chatapi: general refactor (fixes #7207)
  chatapi/src/config/nano.config.ts
  chatapi/src/config/openai.config.ts
  chatapi/src/index.ts
  chatapi/src/models/database-actions.model.ts
  chatapi/src/models/db-doc.model.ts
  chatapi/src/services/chat.service.ts
  chatapi/src/services/gpt-prompt.service.ts
  chatapi/src/utils/chat-error.utils.ts
  chatapi/src/utils/db.utils.ts
  chatapi/src/utils/gpt-chat.utils.ts
  chatapi/src/utils/nano-couchdb.ts
  package.json
  src/app/chat/chat.component.ts
  src/app/shared/chat.service.ts
Labels: Review requested, ready to merge

#7291 courses: more responsive overview toolbar (fixes #7290)
  package.json
  src/app/courses/courses.component.html
  src/app/courses/view-courses/courses-view.component.html
  src/app/courses/view-courses/courses-view.component.ts
  src/app/resources/resources.component.html
  src/app/resources/view-resources/resources-view.component.html
  src/app/resources/view-resources/resources-view.component.ts
  src/styles.scss
Labels: ready to merge

#7285 manager: improve settings dashboard (fixes #7284)
  package.json
  src/app/manager-dashboard/manager-dashboard.component.html
  src/app/manager-dashboard/manager-dashboard.component.ts
Labels: ready to merge

#7293 courses: improve margins for filters (fixes #7292)
  package.json
  src/app/courses/courses.component.html
  src/app/courses/courses.scss
Labels: ready to merge

#6999 enterprises: show negative balance in red (fixes #4789)
  package.json
  src/app/teams/teams-view-finances.component.html
  src/app/teams/teams-view-finances.scss
Labels: merge?

#7241 chat: add history (fixes #7237)
  package.json
  src/app/chat/chat-sidebar/chat-sidebar.component.html
  src/app/chat/chat-sidebar/chat-sidebar.component.ts
  src/app/chat/chat-sidebar/chat-sidebar.scss
  src/app/chat/chat-window/chat-window.component.html
  src/app/chat/chat-window/chat-window.component.ts
  src/app/chat/chat-window/chat-window.scss
  src/app/chat/chat.component.html
  src/app/chat/chat.component.ts
  src/app/chat/chat.module.ts
  src/app/chat/chat.scss
  src/app/home/home.module.ts
  src/app/shared/chat.service.ts
Labels: ready to merge

#7300 chat: last is first with auto refresh (fixes #7297)
  package.json
  src/app/chat/chat-sidebar/chat-sidebar.component.html
  src/app/chat/chat-sidebar/chat-sidebar.component.ts
  src/app/chat/chat-window/chat-window.component.html
  src/app/chat/chat-window/chat-window.component.ts
  src/app/shared/chat.service.ts
Labels: ready to merge

#7296 community: change news to voices (fixes #7294)
  package.json
  src/app/community/community.component.html
  src/app/community/community.component.ts
  src/app/community/community.scss
  src/app/news/news-list-item.component.ts
Labels: ready to merge

#7303 chat: improve submission validation (fixes #7302)
  package.json
  src/app/chat/chat-sidebar/chat-sidebar.component.html
  src/app/chat/chat-window/chat-window.component.html
  src/app/chat/chat-window/chat-window.component.ts
Labels: Review requested
