Repository open-learning-exchange/planet, pull requests merged in 2023-09, with the labels that each got.

#7230 chat: stop spinner on error response
  package.json
  src/app/chat/chat.component.ts
Labels: Review requested, ready to merge

#7236 chat: only spin on valid submission (fixes #7235)
  package.json
  src/app/chat/chat.component.html
  src/app/chat/chat.component.ts
Labels: Review requested, ready to merge

#7239 chat: remove unusused messages variable (fixes #7238)
  package.json
  src/app/chat/chat.component.ts
Labels: ready to merge

#7240 chat: clear textarea on submit (fixes #7234)
  package.json
  src/app/chat/chat.component.html
  src/app/chat/chat.component.ts
Labels: ready to merge

#7148 courses: more reactive title bar (fixes #7136)
  package.json
  src/app/courses/courses.component.html
  src/app/courses/courses.component.ts
  src/app/resources/resources.component.html
  src/app/resources/resources.scss
  src/styles.scss
Labels: Review requested, ready to merge

#7250 profile: improve form layout (fixes #7248)
  package.json
  src/app/users/users-update/users-update.component.html
  src/app/users/users-update/users-update.scss
Labels: Review requested, ready to merge

#6998 admin: change upgrade myPlanet text (fixes #5194)
  package.json
  src/app/manager-dashboard/manager-dashboard.component.html
Labels: ready to merge

#7254 courses: progress menu item admin only (fixes #7253)
  package.json
  src/app/courses/courses.component.html
Labels: ready to merge

#7246 chat: implement formatting directive (fixes #7242)
  package.json
  src/app/chat/chat.component.html
  src/app/chat/chat.component.ts
  src/app/shared/chat-output.directive.ts
  src/app/shared/shared-components.module.ts
Labels: Review requested, ready to merge

#7256 courses: refactor towards more responsiveness (fixes #7165)
  package.json
  src/app/courses/courses.component.html
  src/app/courses/courses.component.ts
  src/app/courses/courses.scss
Labels: Review requested, ready to merge

#7258 courses: reactive table resizing (fixes #7260)
  package.json
  src/app/courses/courses.component.html
  src/app/courses/courses.scss
  src/app/resources/resources.component.html
  src/app/resources/resources.scss
  src/styles.scss
Labels: ready to merge

#7262 resources: more responsive mobile view (fixes #7163)
  package.json
  src/app/resources/resources.component.html
  src/app/resources/resources.scss
Labels: ready to merge

#7252 profile: fix icon rendering (fixes #7251)
  package.json
  src/app/users/users-profile/users-profile.component.html
Labels: ready to merge

#7266 courses: more responsive creation page (fixes #7265)
  package.json
  src/app/courses/add-courses/courses-add.scss
  src/app/shared/forms/planet-step-list.scss
Labels: ready to merge

#6997 health: improve prompt text (fixes #6439)
  package.json
  src/app/health/health-event.component.ts
Labels: ready to merge, merge?
