Repository open-learning-exchange/planet, pull requests merged in 2024-12, with the labels that each got.

#7853 teams: smoother deletion snackbar (fixes #7852)
  package.json
  src/app/teams/teams.component.ts
Labels: ready to merge

#7848 enterprises: smoother list checkmark (fixes #5231)
  package.json
  src/app/teams/teams.component.html
Labels: ready to merge

#7847 teams: smoother document deletion (fixes #4956)
  package.json
  src/app/shared/dialogs/dialogs-prompt.component.html
  src/app/teams/teams-view.component.html
Labels: ready to merge

#7876 courses: smoother steps icons (fixes #7870)
  package.json
  src/app/courses/view-courses/courses-view.scss
Labels: ready to merge

#7850 all: december challenge (fixes #7838)
  package.json
  src/app/shared/dialogs/dialogs-announcement.component.html
  src/app/shared/dialogs/dialogs-announcement.component.ts
  src/app/shared/user-challenge-status.service.ts
  src/app/teams/teams.component.ts
Labels: Review requested

#7875 surveys: smoother sorting (fixes #7802)
  package.json
  src/app/submissions/submissions.component.ts
Labels: ready to merge

#7881 chat: smoother textbox size (fixes #7874)
  package.json
  src/app/chat/chat-window/chat-window.scss
Labels: ready to merge

#7873 courses: limit step titles length (fixes #7867)
  package.json
  src/app/courses/add-courses/courses-step.component.html
Labels: ready to merge

#7773 courses: smoother progress navigation (fixes #7769)
  package.json
  src/app/courses/progress-courses/courses-progress-leader.component.html
  src/app/courses/progress-courses/courses-progress-leader.component.ts
Labels: ready to merge

#7879 courses: smoother steps preview title (fixes #7868)
  package.json
  src/app/courses/view-courses/courses-view.component.html
  src/app/courses/view-courses/courses-view.scss
Labels: ready to merge

#7883 all: smoother empty tables (fixes #7882)
  package.json
  src/app/courses/courses.component.html
  src/app/courses/courses.component.ts
  src/app/courses/enroll-courses/courses-enroll.component.html
  src/app/courses/enroll-courses/courses-enroll.component.ts
  src/app/feedback/feedback.component.html
  src/app/feedback/feedback.component.ts
  src/app/health/health-list.component.html
  src/app/health/health-list.component.ts
  src/app/manager-dashboard/certifications/certifications.component.html
  src/app/manager-dashboard/certifications/certifications.component.ts
  src/app/manager-dashboard/manager-fetch.component.html
  src/app/manager-dashboard/manager-fetch.component.ts
  src/app/meetups/meetups.component.html
  src/app/meetups/meetups.component.ts
  src/app/notifications/notifications.component.html
  src/app/notifications/notifications.component.ts
  src/app/resources/resources.component.html
  src/app/resources/resources.component.ts
  src/app/submissions/submissions.component.html
  src/app/submissions/submissions.component.ts
  src/app/surveys/surveys.component.html
  src/app/surveys/surveys.component.ts
  src/app/teams/teams.component.html
  src/app/teams/teams.component.ts
  src/app/users/users-table.component.html
  src/app/users/users.component.html
  src/app/users/users.component.ts
Labels: ready to merge

#7903 surveys: smoother loading (fixes #7877)
  package.json
  src/app/exams/exams-view.component.ts
Labels: ready to merge

#7899 teams: smoother delete message (fixes #7885)
  package.json
  src/app/teams/teams.component.ts
Labels: ready to merge

#7901 courses: smoother filter list (fixes #7880)
  package.json
  src/app/courses/search-courses/courses-search.component.ts
  src/app/resources/search-resources/resources-search.component.ts
Labels: ready to merge

#7897 resources: smoother buttons (fixes #7889)
  package.json
  src/app/resources/resources.component.html
Labels: ready to merge

#7898 enterprises: smoother csv exports (fixes #7887)(fixes #7888)
  package.json
  src/app/teams/teams-reports.component.ts
  src/app/teams/teams-view-finances.component.ts
Labels: ready to merge

#7902 dashboard: smoother drag and drop (fixes #7886)
  package.json
  src/app/dashboard/dashboard-tile.component.html
Labels: ready to merge

#7904 courses: smoother toolbar (fixes #7878)
  package.json
  src/app/courses/view-courses/courses-view.component.html
  src/app/courses/view-courses/courses-view.scss
Labels: ready to merge

#7864 teams: smoother list (fixes #6546)
  package.json
  src/app/teams/teams.scss
Labels: ready to merge

#7908 enterprises: smoother report dialog (fixes #6946)
  package.json
  src/app/teams/teams-reports-dialog.component.html
Labels: ready to merge

#7909 courses: smoother progress title (fixes #7906)
  package.json
  src/app/courses/progress-courses/courses-progress-leader.component.html
Labels: ready to merge

#7914 manager: smoother reports subheading (fixes #4418)
  package.json
  src/app/manager-dashboard/reports/reports-detail.component.html
  src/app/manager-dashboard/reports/reports-detail.scss
Labels: ready to merge

#7916 manager: initial chat reports (fixes #7896)
  package.json
  src/app/manager-dashboard/reports/reports-detail.component.html
  src/app/manager-dashboard/reports/reports-detail.component.ts
  src/app/manager-dashboard/reports/reports.service.ts
  src/app/manager-dashboard/reports/reports.utils.ts
Labels: ready to merge

#7922 courses: smoother titles (fixes #7664)
  package.json
  src/app/courses/courses.component.html
  src/app/courses/courses.scss
Labels: ready to merge

#7926 dashboard: smoother tiles (fixes #7924)
  package.json
  src/app/dashboard/dashboard-tile.component.html
Labels: ready to merge

#7913 manager: smoother myplanet logs (fixes #7634)(fixes #7816)
  package.json
  src/app/home/home-router.module.ts
  src/app/home/home.module.ts
  src/app/manager-dashboard/manager-dashboard-router.module.ts
  src/app/manager-dashboard/manager-dashboard.component.html
  src/app/manager-dashboard/reports/logs-myplanet.component.html
  src/app/manager-dashboard/reports/logs-myplanet.component.ts
  src/app/manager-dashboard/reports/reports-myplanet.component.html
  src/app/manager-dashboard/reports/reports-myplanet.component.ts
Labels: Review requested

#7862 teams: smoother calendar recursions (fixes #7858)
  package.json
  src/app/meetups/add-meetups/meetups-add.component.html
  src/app/meetups/add-meetups/meetups-add.component.ts
  src/app/shared/calendar.component.ts
  src/app/validators/custom-validators.ts
Labels: ready to merge

#7776 resources: smoother collections display (fixes #7772)
  package.json
  src/app/shared/forms/planet-tag-input-dialog.component.html
Labels: ready to merge

#7912 courses: smoother progress export (fixes #7811)
  package.json
  src/app/courses/progress-courses/courses-progress-leader.component.ts
Labels: ready to merge

#7929 resources: smoother navigation (fixes #7927)
  package.json
  src/app/resources/view-resources/resources-view.component.html
  src/app/resources/view-resources/resources-view.scss
Labels: ready to merge

#7931 chat: smoother ux (fixes #7915)
  package.json
  src/app/chat/chat-window/chat-window.component.ts
Labels: ready to merge

#7938 courses: smoother progress navigation (fixes #7911)(fixes #7936)
  package.json
  src/app/courses/progress-courses/courses-progress-chart.component.html
  src/app/courses/progress-courses/courses-progress-learner.component.html
  src/app/courses/progress-courses/courses-progress-learner.component.ts
Labels: ready to merge

#7946 courses: smoother multiple choice (fixes #7939)
  package.json
  src/app/exams/exams-view.component.ts
Labels: Review requested, ready to merge

#7770 community: smoother calendar legend (fixes #6572)
  package.json
  src/app/community/community.component.html
  src/app/community/community.scss
  src/app/shared/calendar.component.ts
  src/app/teams/teams-view.component.html
Labels: ready to merge

#7932 resources: smoother collections (fixes #7928)
  package.json
  src/app/shared/forms/planet-tag-selected-input.component.ts
Labels: ready to merge

#7958 resources: smoother subcollections (fixes #7948)
  package.json
  src/app/shared/forms/planet-tag-input-dialog.component.html
  src/app/shared/forms/planet-tag-input-dialog.component.ts
Labels: ready to merge

#7951 courses: smoother exam preview header (fixes #7949)
  package.json
  src/app/exams/exams-view.component.html
Labels: ready to merge

#7947 all: smoother dialog prompts (fixes #7945)
  package.json
  src/app/shared/dialogs/dialogs-prompt.component.html
  src/app/shared/dialogs/dialogs-prompt.component.ts
Labels: ready to merge

#7967 teams: smoother title overflow (fixes #7964)
  package.json
  src/app/teams/teams-view.component.html
  src/app/teams/teams-view.scss
Labels: ready to merge

#7960 community: smoother calendar event deletion (fixes #5401)
  package.json
  src/app/meetups/meetups.service.ts
Labels: ready to merge

#7943 resources: smoother collections scrolling (fixes #6280)
  package.json
  src/app/shared/forms/planet-tag-input-dialog.component.ts
Labels: ready to merge

#7956 resources: smoother snackbar (fixes #7954)(fixes #7955)
  package.json
  src/app/courses/courses.service.ts
  src/app/resources/resources.service.ts
Labels: ready to merge

#7974 chat: smoother placeholder text (#7973)
  package.json
  src/app/chat/chat-sidebar/chat-sidebar.component.html
  src/app/chat/chat-sidebar/chat-sidebar.scss
Labels: ready to merge

#7981 teams: smoother resources titles (fixes #7978)
  package.json
  src/app/teams/teams-view.scss
Labels: ready to merge

#7984 all: smoother navigation tooltips
  package.json
  src/app/home/home.component.html
Labels: ready to merge

#7988 resources: smoother collections labels (fixes #7983)
  package.json
  src/app/courses/courses.scss
  src/app/resources/resources.scss
Labels: ready to merge

#7801 resources: smoother create (fixes #7798)
  package.json
  src/app/resources/resources-add.component.html
  src/app/resources/resources-add.scss
Labels: ready to merge

#7842 teams: smoother tasks deadlines (fixes #5377)
  package.json
  src/app/tasks/tasks.component.html
  src/app/tasks/tasks.component.ts
  src/app/tasks/tasks.scss
Labels: ready to merge

#7995 mylife: smoother achievements certifications (fixes #7975)
  package.json
  src/app/users/users-achievements/users-achievements.component.html
  src/app/users/users-achievements/users-achievements.scss
Labels: ready to merge

#7997 mylife: smoother achievements spacing (fixes #7996)
  package.json
  src/app/meetups/meetups.service.ts
  src/app/shared/forms/planet-tag-input-dialog.component.ts
  src/app/users/users-achievements/users-achievements.component.html
  src/app/users/users-achievements/users-achievements.scss
Labels: ready to merge

#7999 dashboard: smoother icon colors (fixes #7993)
  package.json
  src/app/dashboard/dashboard-tile.scss
Labels: ready to merge

#8009 chat: smoother full search (fixes #8004)
  package.json
  src/app/chat/chat-sidebar/chat-sidebar.component.html
  src/app/chat/chat-sidebar/chat-sidebar.scss
  src/app/tasks/tasks.component.ts
Labels: ready to merge

#8010 mylife: smoother myhealth toolbar (fixes #8008)
  package.json
  src/app/health/health.component.html
Labels: ready to merge

#8011 mylife: smoother myhealth countdown (fixes #8007)
  package.json
  src/app/health/health-event-dialog.component.html
Labels: ready to merge

#8015 community: smoother leaders tiles (fixes #8005)
  package.json
  src/app/community/community.scss
Labels: ready to merge
