Repository open-learning-exchange/planet, pull requests merged in 2024-11, with the labels that each got.

#7693 community: smoother voices (fixes #7691) (fixes #7682)
  package.json
  src/app/community/community.component.html
  src/app/community/community.component.ts
Labels: ready to merge

#7699 teams: smoother tasks list (fixes #5914)
  package.json
  src/app/teams/teams-view.component.html
Labels: ready to merge

#7701 community: smoother leaders title (fixes #6858)
  package.json
  src/app/teams/teams-member.component.html
Labels: ready to merge

#7704 all: smoother profile join date (fixes #5076)
  package.json
  src/app/users/users-profile/users-profile.component.html
Labels: ready to merge

#7707 resources: smoother loading (fixes #7706)
  package.json
  src/app/resources/view-resources/resources-view.component.html
  src/app/resources/view-resources/resources-view.component.ts
Labels: ready to merge

#7710 teams: smoother finances export (fixed #7702)
  package.json
  src/app/teams/teams-view-finances.component.html
Labels: ready to merge

#7697 enterprises: smoother reports positions (fixes #6981)
  package.json
  src/app/community/community.scss
  src/app/teams/teams-reports.component.html
  src/app/teams/teams-reports.scss
Labels: ready to merge

#7698 resouces: smoother search (fixes #7689)
  package.json
  src/app/shared/table-helpers.ts
Labels: ready to merge

#7711 manager: smoother report steps filter (fixes #7679)
  package.json
  src/app/manager-dashboard/reports/reports-detail.component.ts
Labels: ready to merge

#7708 community: smoother services (fixes #5615)
  package.json
  src/app/community/community.component.html
  src/app/community/community.scss
Labels: ready to merge

#7720 challenges: smoother progress bar label
  src/app/shared/dialogs/dialogs-announcement.component.html
  src/app/shared/dialogs/dialogs-announcement.component.scss
Labels: Review requested

#7718 challenge: dynamic current and target goal
  src/app/shared/dialogs/dialogs-announcement.component.html
  src/app/shared/dialogs/dialogs-announcement.component.ts
Labels: Review requested

#7696 mylife: smoother myhealth limits (fixes #6696)
  package.json
  src/app/health/health-event.component.ts
Labels: ready to merge

#7713 enterprises: smoother finances (fixes #6568)
  package.json
  src/app/teams/teams-view-finances.component.html
  src/app/teams/teams-view-finances.scss
Labels: ready to merge

#7690 all: san pablo november challenge (fixes #7736)
  package.json
  src/app/community/community.component.ts
  src/app/dashboard/dashboard.component.html
  src/app/dashboard/dashboard.component.ts
  src/app/shared/database/pouch-auth.service.ts
  src/app/shared/dialogs/dialogs-announcement.component.html
  src/app/shared/dialogs/dialogs-announcement.component.scss
  src/app/shared/dialogs/dialogs-announcement.component.ts
  src/app/shared/dialogs/planet-dialogs.module.ts
Labels: priority, experimental

#7721 community challenge: added progress indicators
  src/app/shared/dialogs/dialogs-announcement.component.html
  src/app/shared/dialogs/dialogs-announcement.component.scss
Labels: Review requested

#7716 7712 challenge success message trigger mechanics (Not final ui)
  src/app/shared/dialogs/dialogs-announcement.component.html
  src/app/shared/dialogs/dialogs-announcement.component.scss
  src/app/shared/dialogs/dialogs-announcement.component.ts
Labels: discussion

#7738 enterprises: smoother entries counting (fixes #6950)
  package.json
  src/app/shared/table-helpers.ts
  src/app/teams/teams-view.component.html
  src/app/teams/teams-view.component.ts
Labels: ready to merge

#7734 community: smoother services description (fixes #6001)
  package.json
  src/app/community/community-link-dialog.component.ts
  src/app/community/community.component.ts
Labels: ready to merge

#7752 teams: smoother tasks (fixes #6673)
  package.json
  src/app/teams/teams-member.component.html
  src/app/teams/teams-member.component.ts
Labels: ready to merge

#7754 courses: smoother progress export (fixes #7729)
  package.json
  src/app/courses/progress-courses/courses-progress-leader.component.html
Labels: ready to merge

#7763 community: smoother services (fixes #7762)
  package.json
  src/app/community/community.component.html
  src/app/community/community.scss
Labels: ready to merge

#7764 mylife: smoother myhealth data (fixes #6879)
  package.json
  src/app/health/health.component.html
  src/app/health/health.scss
Labels: ready to merge

#7692 community: smoother calendar (fixes #6796)
  package.json
  src/app/landing/landing-home/landing-home.scss
  src/styles/calendar.scss
Labels: ready to merge

#7777 community: smoother description (fixes #6460)
  package.json
  src/app/community/community.component.ts
Labels: ready to merge

#7731 resources: smoother edit title (fixes #7728)
  package.json
  src/app/courses/add-courses/courses-add.component.html
  src/app/courses/add-courses/courses-add.component.ts
  src/app/resources/resources-add.component.html
  src/app/resources/resources-add.component.ts
Labels: ready to merge

#7784 all: smoother `README.md` (fixes #7593)
  README.md
  package.json
Labels: ready to merge

#7786 mylife: smoother myhealth form buttons (fixes #6344)
  package.json
  src/app/health/health-event.component.html
  src/app/health/health-update.component.html
Labels: ready to merge

#7789 all: smoother feedback search (fixes #3823)
  package.json
  src/app/feedback/feedback.component.html
Labels: ready to merge

#7751 all: smoother november challenge (fixes #7741)(fixes #7748)
  package.json
  src/app/community/community.component.ts
  src/app/courses/step-view-courses/courses-step-view.component.ts
  src/app/dashboard/dashboard.component.html
  src/app/dashboard/dashboard.component.ts
  src/app/exams/exams-view.component.ts
  src/app/home/home.component.html
  src/app/home/home.component.ts
  src/app/notifications/notifications.component.html
  src/app/notifications/notifications.component.ts
  src/app/shared/database/pouch-auth.service.ts
  src/app/shared/dialogs/dialogs-announcement.component.html
  src/app/shared/dialogs/dialogs-announcement.component.scss
  src/app/shared/dialogs/dialogs-announcement.component.ts
  src/app/shared/dialogs/dialogs-chat-share.component.ts
  src/app/shared/dialogs/planet-dialogs.module.ts
  src/app/shared/user-challenge-status.service.ts
Labels: Review requested

#7781 courses: smoother steps loading (fixes #7779)
  package.json
  src/app/courses/step-view-courses/courses-step-view.component.html
  src/app/courses/step-view-courses/courses-step-view.component.ts
  src/app/exams/exams-view.component.html
  src/app/exams/exams-view.component.ts
Labels: ready to merge

#7778 resources: smoother collection tags (fixes #5776)
  package.json
  src/app/shared/forms/planet-tag-input-dialog.component.ts
Labels: ready to merge

#7783 mylife: smoother achievements (fixes #7782)
  package.json
  src/app/users/users-achievements/users-achievements.component.html
  src/app/users/users-achievements/users-achievements.scss
Labels: ready to merge

#7793 teams: smoother voices creation (fixes #4800)
  package.json
  src/app/shared/forms/planet-markdown-textbox.scss
Labels: ready to merge

#7765 dashboard: complete profile reminder (fixes #7758)
  package.json
  src/app/dashboard/dashboard.component.html
  src/app/dashboard/dashboard.component.ts
  src/app/dashboard/dashboard.scss
  src/app/shared/user.service.ts
Labels: ready to merge

#7824 all: smoother challenge validation (fixes #7822)
  package.json
  src/app/shared/dialogs/dialogs-announcement.component.html
  src/app/shared/dialogs/dialogs-announcement.component.ts
  src/app/shared/user-challenge-status.service.ts
Labels: Review requested

#7792 dashboard: smoother avatar linking (fixes #4532)
  package.json
  src/app/dashboard/dashboard.component.html
  src/app/dashboard/dashboard.component.ts
Labels: ready to merge

#7810 all: smoother feedback buttons (fixes #7825)
  package.json
  src/app/feedback/feedback-view.component.html
Labels: ready to merge

#7817 courses: add participants export (fixes #7815)
  package.json
  src/app/courses/enroll-courses/courses-enroll.component.html
  src/app/courses/enroll-courses/courses-enroll.component.ts
Labels: ready to merge

#7828 chat: smoother share (fixes #7812)
  package.json
  src/app/chat/chat-sidebar/chat-sidebar.component.ts
  src/app/shared/dialogs/dialogs-chat-share.component.ts
Labels: ready to merge

#7814 chat: smoother provider switching (fixes #7638)(fixes #7809)
  package.json
  src/app/chat/chat-sidebar/chat-sidebar.component.ts
  src/app/chat/chat-window/chat-window.component.ts
  src/app/chat/chat.component.ts
  src/app/shared/chat.service.ts
Labels: ready to merge

#7808 courses: smoother steps loading (fixes #7780)
  package.json
  src/app/courses/step-view-courses/courses-step-view.component.ts
Labels: ready to merge

#7832 all: smoother challenge chat select (fixes #7813)
  package.json
  src/app/chat/chat-sidebar/chat-sidebar.component.ts
Labels: ready to merge

#7834 mylife: smoother myhealth form (fixes #7833)
  package.json
  src/app/health/health.constants.ts
  src/app/shared/label.component.ts
Labels: ready to merge

#7837 teams: smoother joining (fixes #4530)
  package.json
  src/app/teams/teams.component.ts
Labels: ready to merge

#7649 courses: smoother submissions toolbar (fixes #7631)
  package.json
  src/app/submissions/submission.component.scss
  src/app/submissions/submissions.component.html
  src/app/submissions/submissions.component.ts
Labels: ready to merge

#7840 courses: smoother details creation date (fixes #7839)
  package.json
  src/app/courses/view-courses/courses-view-detail.component.html
Labels: ready to merge

#7844 chat: smoother input autofocus (fixes #7836)
  package.json
  src/app/chat/chat-window/chat-window.component.html
  src/app/chat/chat-window/chat-window.component.ts
Labels: ready to merge
