Repository open-learning-exchange/planet, pull requests merged in 2025-09, with the labels that each got.

#9052 manager: smoother reports navigation filter clearing (fixes #9022)
  package.json
  src/app/manager-dashboard/reports/logs-myplanet.component.html
  src/app/manager-dashboard/reports/logs-myplanet.component.ts
  src/app/manager-dashboard/reports/reports-myplanet.component.html
  src/app/manager-dashboard/reports/reports-myplanet.component.ts
Labels: ready to merge

#9065 teams: less voices response is more (fixes #9063)
  package.json
  src/app/news/news-list-item.component.ts
  src/app/news/news-list.component.ts
Labels: priority, ready to merge

#9050 manager: smoother voices summary export (fixes #9049)
  package.json
  src/app/manager-dashboard/reports/reports-detail.component.ts
  src/app/shared/csv.service.ts
Labels: ready to merge

#9116 manager: smoother myplanet reports (fixes #9114)
  package.json
  src/app/home/home.module.ts
  src/app/manager-dashboard/manager-dashboard-router.module.ts
  src/app/manager-dashboard/manager-dashboard.module.ts
  src/app/manager-dashboard/reports/myplanet/logs-myplanet.component.html
  src/app/manager-dashboard/reports/myplanet/logs-myplanet.component.scss
  src/app/manager-dashboard/reports/myplanet/logs-myplanet.component.ts
  src/app/manager-dashboard/reports/myplanet/myplanet-table.component.html
  src/app/manager-dashboard/reports/myplanet/myplanet-table.component.ts
  src/app/manager-dashboard/reports/myplanet/reports-myplanet.component.html
  src/app/manager-dashboard/reports/myplanet/reports-myplanet.component.scss
  src/app/manager-dashboard/reports/myplanet/reports-myplanet.component.ts
  src/app/shared/shared-components.module.ts
Labels: ready to merge

#9118 actions: smoother claude workflow (fixes #9117)
  .github/workflows/claude.yml
  package.json
Labels: ready to merge

#9122 teams: smoother survey birthyear input (fixes #9119)
  package.json
  src/app/users/users-update/users-update.component.html
  src/app/users/users-update/users-update.component.ts
Labels: ready to merge

#9136 community: smoother services description removing (fixes #9095)
  package.json
  src/app/community/community.component.html
Labels: ready to merge

#9164 all: less planet component is more (fixes #9168)
  package.json
  src/app/home/home.module.ts
  src/app/home/planet.component.html
  src/app/home/planet.component.ts
Labels: ready to merge, codex, less
